<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#索引与数据选择" data-toc-modified-id="索引与数据选择-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>索引与数据选择</a></span></li></ul></div>

In [2]:
import pandas as pd
pd.__version__

'0.23.4'

In [4]:
# 数据来源：https://www.kaggle.com/jessemostipak/hotel-booking-demand
data = pd.read_csv(r'datasets\hotel_bookings.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
hotel                             119390 non-null object
is_canceled                       119390 non-null int64
lead_time                         119390 non-null int64
arrival_date_year                 119390 non-null int64
arrival_date_month                119390 non-null object
arrival_date_week_number          119390 non-null int64
arrival_date_day_of_month         119390 non-null int64
stays_in_weekend_nights           119390 non-null int64
stays_in_week_nights              119390 non-null int64
adults                            119390 non-null int64
children                          119386 non-null float64
babies                            119390 non-null int64
meal                              119390 non-null object
country                           118902 non-null object
market_segment                    119390 non-null object
distribution_channel              119390 non-null object
is_repeated_guest                 119390 non-null int64
previous_cancellations            119390 non-null int64
previous_bookings_not_canceled    119390 non-null int64
reserved_room_type                119390 non-null object
assigned_room_type                119390 non-null object
booking_changes                   119390 non-null int64
deposit_type                      119390 non-null object
agent                             103050 non-null float64
company                           6797 non-null float64
days_in_waiting_list              119390 non-null int64
customer_type                     119390 non-null object
adr                               119390 non-null float64
required_car_parking_spaces       119390 non-null int64
total_of_special_requests         119390 non-null int64
reservation_status                119390 non-null object
reservation_status_date           119390 non-null object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

#### 索引与数据选择

In [17]:
# DataFrame可以通过传入列名称直接选取数据，这是基本索引
data[['adr','customer_type']].head()

    adr customer_type
0   0.0     Transient
1   0.0     Transient
2  75.0     Transient
3  75.0     Transient
4  98.0     Transient

In [24]:
# 也可以通过属性直接访问列
data.lead_time

0    342
1    737
2      7
3     13
4     14
Name: lead_time, dtype: int64

In [9]:
# loc是基于名称的索引，先行后列地指定行和列的索引名称
data.loc[5:120:2]   # 传入行索引，列默认全选

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.00,0,1,Check-Out,2015-07-03
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.50,0,0,Canceled,2015-04-22
11,Resort Hotel,0,35,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,145.00,0,0,Check-Out,2015-07-05
13,Resort Hotel,0,18,2015,July,27,1,0,4,2,...,No Deposit,241.0,NaN,0,Transient,154.77,0,1,Check-Out,2015-07-05
15,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,97.00,0,3,Check-Out,2015-07-05
17,Resort Hotel,0,12,2015,July,27,1,0,1,2,...,No Deposit,240.0,NaN,0,Transient,88.20,0,0,Check-Out,2015-07-02
19,Resort Hotel,0,7,2015,July,27,1,0,4,2,...,No Deposit,250.0,NaN,0,Transient,153.00,0,1,Check-Out,2015-07-05
21,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,No Deposit,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07
23,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,No Deposit,250.0,NaN,0,Transient,99.67,0,1,Check-Out,2015-07-07
25,Resort Hotel,0,78,2015,July,27,1,2,5,2,...,No Deposit,5.0,NaN,0,Transient,63.60,1,0,Check-Out,2015-07-08
27,Resort Hotel,1,60,2015,July,27,1,2,5,2,...,No Deposit,240.0,NaN,0,Transient,107.00,0,2,Canceled,2015-05-11
29,Resort Hotel,0,99,2015,July,27,1,2,5,2,...,No Deposit,240.0,NaN,0,Transient,87.30,1,1,Check-Out,2015-07-08
31,Resort Hotel,0,95,2015,July,27,1,4,11,2,...,No Deposit,241.0,NaN,0,Transient,63.86,0,0,Check-Out,2015-07-16
33,Resort Hotel,0,69,2015,July,27,2,2,4,2,...,No Deposit,175.0,NaN,0,Transient,65.50,0,0,Check-Out,2015-07-08
35,Resort Hotel,1,40,2015,July,27,2,1,3,3,...,No Deposit,241.0,NaN,0,Transient,108.80,0,1,Canceled,2015-06-19
37,Resort Hotel,0,36,2015,July,27,2,1,3,3,...,No Deposit,241.0,NaN,0,Transient,108.80,0,1,Check-Out,2015-07-06
39,Resort Hotel,0,70,2015,July,27,2,2,3,2,...,No Deposit,250.0,NaN,0,Transient,137.00,0,1,Check-Out,2015-07-07
41,Resort Hotel,0,45,2015,July,27,2,2,3,2,...,No Deposit,8.0,NaN,0,Contract,79.50,0,0,Check-Out,2015-07-07
43,Resort Hotel,0,70,2015,July,27,2,2,3,2,...,No Deposit,250.0,NaN,0,Transient,137.00,0,1,Check-Out,2015-07-07
45,Resort Hotel,1,47,2015,July,27,2,2,5,2,...,No Deposit,240.0,NaN,0,Transient,153.00,0,0,Canceled,2015-06-02
47,Resort Hotel,0,113,2015,July,27,2,2,5,2,...,No Deposit,156.0,NaN,0,Transient-Party,82.88,0,2,Check-Out,2015-07-09
49,Resort Hotel,0,50,2015,July,27,2,2,5,2,...,No Deposit,241.0,NaN,0,Transient,119.35,0,1,Check-Out,2015-07-09
51,Resort Hotel,0,93,2015,July,27,2,3,8,2,...,No Deposit,156.0,NaN,0,Contract,56.01,0,0,Check-Out,2015-07-13
53,Resort Hotel,0,3,2015,July,27,2,0,1,2,...,No Deposit,240.0,NaN,0,Transient,88.20,1,0,Check-Out,2015-07-03
55,Resort Hotel,0,1,2015,July,27,2,0,1,2,...,No Deposit,NaN,NaN,0,Transient,107.00,1,2,Check-Out,2015-07-03
57,Resort Hotel,0,0,2015,July,27,2,0,1,2,...,No Deposit,240.0,NaN,0,Transient,117.90,0,2,Check-Out,2015-07-03
59,Resort Hotel,0,14,2015,July,27,2,0,2,2,...,No Deposit,242.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-04
61,Resort Hotel,0,5,2015,July,27,2,0,2,2,...,No Deposit,240.0,NaN,0,Transient,135.00,1,2,Check-Out,2015-07-04
63,Resort Hotel,0,93,2015,July,27,2,0,3,2,...,No Deposit,115.0,NaN,0,Contract,58.95,0,0,Check-Out,2015-07-05
65,Resort Hotel,0,10,2015,July,27,3,0,2,2,...,No Deposit,240.0,NaN,0,Transient,153.00,1,0,Check-Out,2015-07-05
67,Resort Hotel,0,51,2015,July,27,3,0,2,2,...,No Deposit,242.0,NaN,0,Transient,97.00,0,0,Check-Out,2015-07-05
69,Resort Hotel,1,63,2015,July,27,3,0,2,2,...,No Deposit,240.0,NaN,0,Transient,82.00,0,2,Canceled,2015-06-18
71,Resort Hotel,1,101,2015,July,27,3,0,2,2,...,No Deposit,240.0,NaN,0,Transient,73.80,0,1,Canceled,2015-06-12
73,Resort Hotel,0,15,2015,July,27,3,0,2,2,...,No Deposit,240.0,NaN,0,Transient,114.50,0,0,Check-Out,2015-07-05
75,Resort Hotel,0,3,2015,July,27,3,1,2,2,...,No Deposit,240.0,NaN,0,Transient,90.90,1,0,Check-Out,2015-07-06
77,Resort Hotel,0,2,2015,July,27,3,2,2,1,...,No Deposit,240.0,NaN,0,Transient,122.00,0,0,Check-Out,2015-07-07
79,Resort Hotel,0,81,2015,July,27,3,2,6,3,...,No Deposit,5.0,NaN,0,Transient,85.86,0,0,Check-Out,2015-07-11
81,Resort Hotel,1,368,2015,July,27,3,3,7,2,...,No Deposit,40.0,NaN,0,Contract,55.68,0,0,Canceled,2015-05-19
83,Resort Hotel,1,81,2015,July,27,3,3,7,2,...,No Deposit,250.0,NaN,0,Transient,124.00,0,1,Canceled,2015-06-09
85,Resort Hotel,0,324,2015,July,27,3,4,10,2,...,No Deposit,40.0,NaN,0,Contract,134.73,0,0,Check-Out,2015-07-17
87,Resort Hotel,1,79,2015,July,27,3,6,15,2,...,No Deposit,242.0,NaN,0,Transient,108.73,0,2,Canceled,2015-04-15
89,Resort Hotel,0,9,2015,July,27,3,0,1,2,...,No Deposit,240.0,NaN,0,Transient,98.00,1,2,Check-Out,2015-07-04
91,Resort Hotel,0,21,2015,July,27,3,0,1,2,...,No Deposit,240.0,NaN,0,Transient,123.00,0,0,Check-Out,2015-07-04
93,Resort Hotel,0,109,2015,July,27,3,0,1,2,...,No Deposit,240.0,NaN,0,Transient,123.00,0,2,Check-Out,2015-07-04
95,Resort Hotel,1,72,2015,July,27,3,0,2,2,...,No Deposit,240.0,NaN,0,Transient,73.80,0,1,Canceled,2015-06-29
97,Resort Hotel,0,63,2015,July,27,3,2,5,3,...,No Deposit,105.0,NaN,0,Transient,196.54,0,1,Check-Out,2015-07-10
99,Resort Hotel,0,102,2015,July,27,3,2,5,2,...,No Deposit,250.0,NaN,0,Transient,90.95,0,0,Check-Out,2015-07-10
101,Resort Hotel,0,98,2015,July,27,4,2,1,2,...,No Deposit,8.0,NaN,0,Transient,71.55,1,0,Check-Out,2015-07-07
103,Resort Hotel,0,95,2015,July,27,4,2,4,2,...,No Deposit,240.0,NaN,0,Transient,85.80,1,2,Check-Out,2015-07-10
105,Resort Hotel,1,26,2015,July,27,4,2,5,2,...,No Deposit,240.0,NaN,0,Transient,163.00,0,0,Canceled,2015-06-09
107,Resort Hotel,1,102,2015,July,27,4,2,5,2,...,No Deposit,240.0,NaN,0,Transient,110.70,0,1,Canceled,2015-04-22
109,Resort Hotel,0,102,2015,July,27,4,2,5,2,...,No Deposit,240.0,NaN,0,Transient,73.80,0,2,Check-Out,2015-07-11
111,Resort Hotel,0,78,2015,July,27,4,2,5,2,...,No Deposit,240.0,NaN,0,Transient,139.00,0,2,Check-Out,2015-07-11
113,Resort Hotel,0,29,2015,July,27,4,2,6,3,...,No Deposit,241.0,NaN,0,Transient,116.50,0,1,Check-Out,2015-07-12
115,Resort Hotel,0,109,2015,July,27,4,2,6,2,...,No Deposit,240.0,NaN,0,Transient,123.00,0,1,Check-Out,2015-07-12
117,Resort Hotel,0,92,2015,July,27,4,4,6,2,...,No Deposit,40.0,NaN,0,Contract,71.55,0,1,Check-Out,2015-07-14
119,Resort Hotel,0,2,2015,July,27,4,0,1,2,...,No Deposit,240.0,NaN,0,Transient,163.00,1,0,Check-Out,2015-07-05

In [13]:
# loc的另一种用法
data.loc[5:10, ['agent', 'company']]

    agent  company
5   240.0      NaN
6     NaN      NaN
7   303.0      NaN
8   240.0      NaN
9    15.0      NaN
10  240.0      NaN

In [25]:
data.loc[5:10, 'hotel': 'company']

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,Direct,0,0,0,C,C,0,No Deposit,NaN,NaN
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,Direct,0,0,0,C,C,0,No Deposit,303.0,NaN
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,TA/TO,0,0,0,D,D,0,No Deposit,15.0,NaN
10,Resort Hotel,1,23,2015,July,27,1,0,4,2,...,TA/TO,0,0,0,E,E,0,No Deposit,240.0,NaN

In [19]:
# iloc是基于位置的索引,先行后列地指定行和列的位置 
data.iloc[:,3:5].head()

   arrival_date_year arrival_date_month
0               2015               July
1               2015               July
2               2015               July
3               2015               July
4               2015               July

In [28]:
# 可以单取一行数据
data.iloc[2]

{'adr': 75.0,
 'adults': 1,
 'agent': nan,
 'arrival_date_day_of_month': 1,
 'arrival_date_month': 'July',
 'arrival_date_week_number': 27,
 'arrival_date_year': 2015,
 'assigned_room_type': 'C',
 'babies': 0,
 'booking_changes': 0,
 'children': 0.0,
 'company': nan,
 'country': 'GBR',
 'customer_type': 'Transient',
 'days_in_waiting_list': 0,
 'deposit_type': 'No Deposit',
 'distribution_channel': 'Direct',
 'hotel': 'Resort Hotel',
 'is_canceled': 0,
 'is_repeated_guest': 0,
 'lead_time': 7,
 'market_segment': 'Direct',
 'meal': 'BB',
 'previous_bookings_not_canceled': 0,
 'previous_cancellations': 0,
 'required_car_parking_spaces': 0,
 'reservation_status': 'Check-Out',
 'reservation_status_date': '2015-07-02',
 'reserved_room_type': 'A',
 'stays_in_week_nights': 1,
 'stays_in_weekend_nights': 0,
 'total_of_special_requests': 0}

In [22]:
data.iloc[2:100, :].head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03

In [30]:
# []、.loc、.iloc 可以接收一个“索引器”
data[data['adr'] > data['adr'].mean()]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.00,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.00,0,1,Check-Out,2015-07-03
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.50,0,0,Canceled,2015-04-22
10,Resort Hotel,1,23,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,123.00,0,0,Canceled,2015-06-23
11,Resort Hotel,0,35,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,145.00,0,0,Check-Out,2015-07-05
13,Resort Hotel,0,18,2015,July,27,1,0,4,2,...,No Deposit,241.0,NaN,0,Transient,154.77,0,1,Check-Out,2015-07-05
18,Resort Hotel,0,0,2015,July,27,1,0,1,2,...,No Deposit,NaN,110.0,0,Transient,107.42,0,0,Check-Out,2015-07-02
19,Resort Hotel,0,7,2015,July,27,1,0,4,2,...,No Deposit,250.0,NaN,0,Transient,153.00,0,1,Check-Out,2015-07-05
27,Resort Hotel,1,60,2015,July,27,1,2,5,2,...,No Deposit,240.0,NaN,0,Transient,107.00,0,2,Canceled,2015-05-11
32,Resort Hotel,1,96,2015,July,27,1,2,8,2,...,No Deposit,NaN,NaN,0,Transient,108.30,0,2,Canceled,2015-05-29
34,Resort Hotel,1,45,2015,July,27,2,1,3,3,...,No Deposit,241.0,NaN,0,Transient,108.80,0,1,Canceled,2015-05-19
35,Resort Hotel,1,40,2015,July,27,2,1,3,3,...,No Deposit,241.0,NaN,0,Transient,108.80,0,1,Canceled,2015-06-19
37,Resort Hotel,0,36,2015,July,27,2,1,3,3,...,No Deposit,241.0,NaN,0,Transient,108.80,0,1,Check-Out,2015-07-06
38,Resort Hotel,1,43,2015,July,27,2,1,3,3,...,No Deposit,241.0,NaN,0,Transient,108.80,0,0,Canceled,2015-05-23
39,Resort Hotel,0,70,2015,July,27,2,2,3,2,...,No Deposit,250.0,NaN,0,Transient,137.00,0,1,Check-Out,2015-07-07
40,Resort Hotel,1,45,2015,July,27,2,2,3,2,...,No Deposit,241.0,NaN,0,Transient,117.81,0,0,Canceled,2015-05-18
42,Resort Hotel,0,16,2015,July,27,2,2,3,2,...,No Deposit,NaN,NaN,0,Transient,123.00,0,0,Check-Out,2015-07-07
43,Resort Hotel,0,70,2015,July,27,2,2,3,2,...,No Deposit,250.0,NaN,0,Transient,137.00,0,1,Check-Out,2015-07-07
44,Resort Hotel,0,107,2015,July,27,2,2,5,2,...,No Deposit,240.0,NaN,0,Transient,110.70,0,2,Check-Out,2015-07-09
45,Resort Hotel,1,47,2015,July,27,2,2,5,2,...,No Deposit,240.0,NaN,0,Transient,153.00,0,0,Canceled,2015-06-02
49,Resort Hotel,0,50,2015,July,27,2,2,5,2,...,No Deposit,241.0,NaN,0,Transient,119.35,0,1,Check-Out,2015-07-09
52,Resort Hotel,0,76,2015,July,27,2,4,10,2,...,No Deposit,243.0,NaN,0,Contract,110.70,0,0,Check-Out,2015-07-16
54,Resort Hotel,0,1,2015,July,27,2,0,1,2,...,No Deposit,240.0,NaN,0,Transient,147.00,1,0,Check-Out,2015-07-03
55,Resort Hotel,0,1,2015,July,27,2,0,1,2,...,No Deposit,NaN,NaN,0,Transient,107.00,1,2,Check-Out,2015-07-03
56,Resort Hotel,0,0,2015,July,27,2,0,1,2,...,No Deposit,NaN,NaN,0,Transient,147.00,0,0,Check-Out,2015-07-03
57,Resort Hotel,0,0,2015,July,27,2,0,1,2,...,No Deposit,240.0,NaN,0,Transient,117.90,0,2,Check-Out,2015-07-03
58,Resort Hotel,0,0,2015,July,27,2,0,1,2,...,No Deposit,NaN,NaN,0,Transient,123.00,0,0,Check-Out,2015-07-03
60,Resort Hotel,0,10,2015,July,27,2,0,2,2,...,No Deposit,241.0,NaN,0,Transient,117.81,0,0,Check-Out,2015-07-04
61,Resort Hotel,0,5,2015,July,27,2,0,2,2,...,No Deposit,240.0,NaN,0,Transient,135.00,1,2,Check-Out,2015-07-04
62,Resort Hotel,0,17,2015,July,27,2,0,3,2,...,No Deposit,250.0,NaN,0,Transient,133.00,0,1,Check-Out,2015-07-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119340,City Hotel,0,110,2017,August,35,29,0,5,2,...,No Deposit,14.0,NaN,0,Transient,171.00,0,2,Check-Out,2017-09-03
119341,City Hotel,0,181,2017,August,35,29,0,5,1,...,No Deposit,9.0,NaN,0,Transient,126.90,0,2,Check-Out,2017-09-03
119342,City Hotel,0,63,2017,August,35,31,0,3,3,...,No Deposit,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03
119344,City Hotel,0,31,2017,August,35,31,0,3,2,...,No Deposit,9.0,NaN,0,Transient,152.67,0,1,Check-Out,2017-09-03
119346,City Hotel,0,45,2017,August,35,27,2,5,2,...,No Deposit,9.0,NaN,0,Transient,183.86,0,2,Check-Out,2017-09-03
119347,City Hotel,0,63,2017,August,35,31,0,3,3,...,No Deposit,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03
119348,City Hotel,0,63,2017,August,35,31,0,3,3,...,No Deposit,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03
119349,City Hotel,0,186,2017,August,35,31,0,3,2,...,No Deposit,9.0,NaN,0,Transient,126.00,0,2,Check-Out,2017-09-03
119350,City Hotel,0,286,2017,August,35,30,0,4,2,...,No Deposit,9.0,NaN,0,Transient,112.05,0,3,Check-Out,2017-09-03
119351,City Hotel,0,72,2017,August,35,31,0,3,2,...,No Deposit,14.0,NaN,0,Transient,134.82,0,1,Check-Out,2017-09-03
119352,City Hotel,0,63,2017,August,35,31,0,3,3,...,No Deposit,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03
119353,City Hotel,0,63,2017,August,35,31,0,3,3,...,No Deposit,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03
119354,City Hotel,0,63,2017,August,35,31,0,3,3,...,No Deposit,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03
119355,City Hotel,0,111,2017,August,35,29,1,5,1,...,No Deposit,14.0,NaN,0,Transient,135.00,0,2,Check-Out,2017-09-04
119356,City Hotel,0,111,2017,August,35,29,1,5,2,...,No Deposit,14.0,NaN,0,Transient,135.00,0,1,Check-Out,2017-09-04
119358,City Hotel,0,135,2017,August,35,30,1,4,2,...,No Deposit,14.0,NaN,0,Transient,143.10,0,1,Check-Out,2017-09-04
119359,City Hotel,0,63,2017,August,35,31,1,3,2,...,No Deposit,9.0,NaN,0,Transient,133.50,0,1,Check-Out,2017-09-04
119360,City Hotel,0,195,2017,August,35,29,1,5,2,...,No Deposit,9.0,NaN,0,Transient,117.00,0,1,Check-Out,2017-09-04
119362,City Hotel,0,198,2017,August,35,29,1,5,2,...,No Deposit,9.0,NaN,0,Transient,119.17,0,2,Check-Out,2017-09-04
119365,City Hotel,0,54,2017,August,35,27,3,5,1,...,No Deposit,14.0,NaN,0,Transient,266.75,0,1,Check-Out,2017-09-04
119370,City Hotel,0,201,2017,August,35,30,1,4,1,...,No Deposit,9.0,NaN,0,Transient,108.00,0,2,Check-Out,2017-09-04
119374,City Hotel,0,201,2017,August,35,29,1,5,2,...,No Deposit,9.0,NaN,0,Transient,117.00,0,2,Check-Out,2017-09-04
119376,City Hotel,0,165,2017,August,35,29,1,5,3,...,No Deposit,9.0,NaN,0,Transient,209.25,0,3,Check-Out,2017-09-04
119379,City Hotel,0,109,2017,August,35,31,1,3,2,...,No Deposit,9.0,NaN,0,Transient,155.00,0,1,Check-Out,2017-09-04
119380,City Hotel,0,44,2017,August,35,31,1,3,2,...,No Deposit,9.0,NaN,0,Transient,140.75,0,1,Check-Out,2017-09-04
119382,City Hotel,0,135,2017,August,35,30,2,4,3,...,No Deposit,7.0,NaN,0,Transient,209.00,0,0,Check-Out,2017-09-05
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [31]:
data.loc[lambda data : data.adr > 70, :]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.00,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.00,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.00,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.50,0,0,Canceled,2015-04-22
10,Resort Hotel,1,23,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,123.00,0,0,Canceled,2015-06-23
11,Resort Hotel,0,35,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,145.00,0,0,Check-Out,2015-07-05
12,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,97.00,0,3,Check-Out,2015-07-05
13,Resort Hotel,0,18,2015,July,27,1,0,4,2,...,No Deposit,241.0,NaN,0,Transient,154.77,0,1,Check-Out,2015-07-05
14,Resort Hotel,0,37,2015,July,27,1,0,4,2,...,No Deposit,241.0,NaN,0,Transient,94.71,0,0,Check-Out,2015-07-05
15,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,97.00,0,3,Check-Out,2015-07-05
16,Resort Hotel,0,37,2015,July,27,1,0,4,2,...,No Deposit,8.0,NaN,0,Contract,97.50,0,0,Check-Out,2015-07-05
17,Resort Hotel,0,12,2015,July,27,1,0,1,2,...,No Deposit,240.0,NaN,0,Transient,88.20,0,0,Check-Out,2015-07-02
18,Resort Hotel,0,0,2015,July,27,1,0,1,2,...,No Deposit,NaN,110.0,0,Transient,107.42,0,0,Check-Out,2015-07-02
19,Resort Hotel,0,7,2015,July,27,1,0,4,2,...,No Deposit,250.0,NaN,0,Transient,153.00,0,1,Check-Out,2015-07-05
20,Resort Hotel,0,37,2015,July,27,1,1,4,1,...,No Deposit,241.0,NaN,0,Transient,97.29,0,1,Check-Out,2015-07-06
21,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,No Deposit,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07
22,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,No Deposit,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07
23,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,No Deposit,250.0,NaN,0,Transient,99.67,0,1,Check-Out,2015-07-07
24,Resort Hotel,0,127,2015,July,27,1,2,5,2,...,No Deposit,115.0,NaN,0,Contract,94.95,0,1,Check-Out,2015-07-01
26,Resort Hotel,0,48,2015,July,27,1,2,5,2,...,No Deposit,8.0,NaN,0,Contract,79.50,0,0,Check-Out,2015-07-08
27,Resort Hotel,1,60,2015,July,27,1,2,5,2,...,No Deposit,240.0,NaN,0,Transient,107.00,0,2,Canceled,2015-05-11
28,Resort Hotel,0,77,2015,July,27,1,2,5,2,...,No Deposit,240.0,NaN,0,Transient,94.00,0,0,Check-Out,2015-07-08
29,Resort Hotel,0,99,2015,July,27,1,2,5,2,...,No Deposit,240.0,NaN,0,Transient,87.30,1,1,Check-Out,2015-07-08
32,Resort Hotel,1,96,2015,July,27,1,2,8,2,...,No Deposit,NaN,NaN,0,Transient,108.30,0,2,Canceled,2015-05-29
34,Resort Hotel,1,45,2015,July,27,2,1,3,3,...,No Deposit,241.0,NaN,0,Transient,108.80,0,1,Canceled,2015-05-19
35,Resort Hotel,1,40,2015,July,27,2,1,3,3,...,No Deposit,241.0,NaN,0,Transient,108.80,0,1,Canceled,2015-06-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119360,City Hotel,0,195,2017,August,35,29,1,5,2,...,No Deposit,9.0,NaN,0,Transient,117.00,0,1,Check-Out,2017-09-04
119361,City Hotel,0,100,2017,August,35,31,1,3,2,...,No Deposit,16.0,NaN,0,Transient,95.85,0,0,Check-Out,2017-09-04
119362,City Hotel,0,198,2017,August,35,29,1,5,2,...,No Deposit,9.0,NaN,0,Transient,119.17,0,2,Check-Out,2017-09-04
119363,City Hotel,0,212,2017,August,35,28,2,5,2,...,No Deposit,7.0,NaN,0,Transient,92.17,0,1,Check-Out,2017-09-04
119364,City Hotel,0,212,2017,August,35,28,2,5,2,...,No Deposit,7.0,NaN,0,Transient,92.17,0,2,Check-Out,2017-09-04
119365,City Hotel,0,54,2017,August,35,27,3,5,1,...,No Deposit,14.0,NaN,0,Transient,266.75,0,1,Check-Out,2017-09-04
119366,City Hotel,0,210,2017,August,35,28,2,5,2,...,No Deposit,7.0,NaN,0,Transient,85.59,0,1,Check-Out,2017-09-04
119367,City Hotel,0,212,2017,August,35,28,2,5,2,...,No Deposit,7.0,NaN,0,Transient,85.59,0,0,Check-Out,2017-09-04
119368,City Hotel,0,261,2017,August,35,30,1,4,2,...,No Deposit,14.0,NaN,0,Transient,99.00,0,0,Check-Out,2017-09-04
119369,City Hotel,0,207,2017,August,34,25,3,7,2,...,No Deposit,14.0,NaN,0,Transient,96.25,0,2,Check-Out,2017-09-04
119370,City Hotel,0,201,2017,August,35,30,1,4,1,...,No Deposit,9.0,NaN,0,Transient,108.00,0,2,Check-Out,2017-09-04
119371,City Hotel,0,175,2017,August,35,31,1,3,2,...,No Deposit,42.0,NaN,0,Transient,86.85,0,2,Check-Out,2017-09-04
119372,City Hotel,0,175,2017,August,35,31,1,3,1,...,No Deposit,42.0,NaN,0,Transient,82.35,0,1,Check-Out,2017-09-04
119373,City Hotel,0,175,2017,August,35,31,1,3,1,...,No Deposit,42.0,NaN,0,Transient,82.35,0,1,Check-Out,2017-09-04
119374,City Hotel,0,201,2017,August,35,29,1,5,2,...,No Deposit,9.0,NaN,0,Transient,117.00,0,2,Check-Out,2017-09-04
119375,City Hotel,0,200,2017,August,35,30,1,4,2,...,No Deposit,16.0,NaN,0,Transient,85.50,0,1,Check-Out,2017-09-04
119376,City Hotel,0,165,2017,August,35,29,1,5,3,...,No Deposit,9.0,NaN,0,Transient,209.25,0,3,Check-Out,2017-09-04
119377,City Hotel,0,185,2017,August,35,30,1,4,2,...,No Deposit,9.0,NaN,0,Transient,99.00,0,1,Check-Out,2017-09-04
119378,City Hotel,0,247,2017,August,35,31,1,3,2,...,No Deposit,42.0,NaN,0,Transient,86.85,0,0,Check-Out,2017-09-04
119379,City Hotel,0,109,2017,August,35,31,1,3,2,...,No Deposit,9.0,NaN,0,Transient,155.00,0,1,Check-Out,2017-09-04
119380,City Hotel,0,44,2017,August,35,31,1,3,2,...,No Deposit,9.0,NaN,0,Transient,140.75,0,1,Check-Out,2017-09-04
119381,City Hotel,0,188,2017,August,35,31,2,3,2,...,No Deposit,14.0,NaN,0,Transient,99.00,0,0,Check-Out,2017-09-05
119382,City Hotel,0,135,2017,August,35,30,2,4,3,...,No Deposit,7.0,NaN,0,Transient,209.00,0,0,Check-Out,2017-09-05
119383,City Hotel,0,164,2017,August,35,31,2,4,2,...,No Deposit,42.0,NaN,0,Transient,87.60,0,0,Check-Out,2017-09-06
119384,City Hotel,0,21,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,2,Check-Out,2017-09-06
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [36]:
# 重建索引
data_reindex = data.copy()
data_reindex.reindex([i for i in range(1, len(data_reindex) + 1)])

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
1,Resort Hotel,0.0,737.0,2015.0,July,27.0,1.0,0.0,0.0,2.0,...,No Deposit,NaN,NaN,0.0,Transient,0.00,0.0,0.0,Check-Out,2015-07-01
2,Resort Hotel,0.0,7.0,2015.0,July,27.0,1.0,0.0,1.0,1.0,...,No Deposit,NaN,NaN,0.0,Transient,75.00,0.0,0.0,Check-Out,2015-07-02
3,Resort Hotel,0.0,13.0,2015.0,July,27.0,1.0,0.0,1.0,1.0,...,No Deposit,304.0,NaN,0.0,Transient,75.00,0.0,0.0,Check-Out,2015-07-02
4,Resort Hotel,0.0,14.0,2015.0,July,27.0,1.0,0.0,2.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,98.00,0.0,1.0,Check-Out,2015-07-03
5,Resort Hotel,0.0,14.0,2015.0,July,27.0,1.0,0.0,2.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,98.00,0.0,1.0,Check-Out,2015-07-03
6,Resort Hotel,0.0,0.0,2015.0,July,27.0,1.0,0.0,2.0,2.0,...,No Deposit,NaN,NaN,0.0,Transient,107.00,0.0,0.0,Check-Out,2015-07-03
7,Resort Hotel,0.0,9.0,2015.0,July,27.0,1.0,0.0,2.0,2.0,...,No Deposit,303.0,NaN,0.0,Transient,103.00,0.0,1.0,Check-Out,2015-07-03
8,Resort Hotel,1.0,85.0,2015.0,July,27.0,1.0,0.0,3.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,82.00,0.0,1.0,Canceled,2015-05-06
9,Resort Hotel,1.0,75.0,2015.0,July,27.0,1.0,0.0,3.0,2.0,...,No Deposit,15.0,NaN,0.0,Transient,105.50,0.0,0.0,Canceled,2015-04-22
10,Resort Hotel,1.0,23.0,2015.0,July,27.0,1.0,0.0,4.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,123.00,0.0,0.0,Canceled,2015-06-23
11,Resort Hotel,0.0,35.0,2015.0,July,27.0,1.0,0.0,4.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,145.00,0.0,0.0,Check-Out,2015-07-05
12,Resort Hotel,0.0,68.0,2015.0,July,27.0,1.0,0.0,4.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,97.00,0.0,3.0,Check-Out,2015-07-05
13,Resort Hotel,0.0,18.0,2015.0,July,27.0,1.0,0.0,4.0,2.0,...,No Deposit,241.0,NaN,0.0,Transient,154.77,0.0,1.0,Check-Out,2015-07-05
14,Resort Hotel,0.0,37.0,2015.0,July,27.0,1.0,0.0,4.0,2.0,...,No Deposit,241.0,NaN,0.0,Transient,94.71,0.0,0.0,Check-Out,2015-07-05
15,Resort Hotel,0.0,68.0,2015.0,July,27.0,1.0,0.0,4.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,97.00,0.0,3.0,Check-Out,2015-07-05
16,Resort Hotel,0.0,37.0,2015.0,July,27.0,1.0,0.0,4.0,2.0,...,No Deposit,8.0,NaN,0.0,Contract,97.50,0.0,0.0,Check-Out,2015-07-05
17,Resort Hotel,0.0,12.0,2015.0,July,27.0,1.0,0.0,1.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,88.20,0.0,0.0,Check-Out,2015-07-02
18,Resort Hotel,0.0,0.0,2015.0,July,27.0,1.0,0.0,1.0,2.0,...,No Deposit,NaN,110.0,0.0,Transient,107.42,0.0,0.0,Check-Out,2015-07-02
19,Resort Hotel,0.0,7.0,2015.0,July,27.0,1.0,0.0,4.0,2.0,...,No Deposit,250.0,NaN,0.0,Transient,153.00,0.0,1.0,Check-Out,2015-07-05
20,Resort Hotel,0.0,37.0,2015.0,July,27.0,1.0,1.0,4.0,1.0,...,No Deposit,241.0,NaN,0.0,Transient,97.29,0.0,1.0,Check-Out,2015-07-06
21,Resort Hotel,0.0,72.0,2015.0,July,27.0,1.0,2.0,4.0,2.0,...,No Deposit,250.0,NaN,0.0,Transient,84.67,0.0,1.0,Check-Out,2015-07-07
22,Resort Hotel,0.0,72.0,2015.0,July,27.0,1.0,2.0,4.0,2.0,...,No Deposit,250.0,NaN,0.0,Transient,84.67,0.0,1.0,Check-Out,2015-07-07
23,Resort Hotel,0.0,72.0,2015.0,July,27.0,1.0,2.0,4.0,2.0,...,No Deposit,250.0,NaN,0.0,Transient,99.67,0.0,1.0,Check-Out,2015-07-07
24,Resort Hotel,0.0,127.0,2015.0,July,27.0,1.0,2.0,5.0,2.0,...,No Deposit,115.0,NaN,0.0,Contract,94.95,0.0,1.0,Check-Out,2015-07-01
25,Resort Hotel,0.0,78.0,2015.0,July,27.0,1.0,2.0,5.0,2.0,...,No Deposit,5.0,NaN,0.0,Transient,63.60,1.0,0.0,Check-Out,2015-07-08
26,Resort Hotel,0.0,48.0,2015.0,July,27.0,1.0,2.0,5.0,2.0,...,No Deposit,8.0,NaN,0.0,Contract,79.50,0.0,0.0,Check-Out,2015-07-08
27,Resort Hotel,1.0,60.0,2015.0,July,27.0,1.0,2.0,5.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,107.00,0.0,2.0,Canceled,2015-05-11
28,Resort Hotel,0.0,77.0,2015.0,July,27.0,1.0,2.0,5.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,94.00,0.0,0.0,Check-Out,2015-07-08
29,Resort Hotel,0.0,99.0,2015.0,July,27.0,1.0,2.0,5.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,87.30,1.0,1.0,Check-Out,2015-07-08
30,Resort Hotel,0.0,118.0,2015.0,July,27.0,1.0,4.0,10.0,1.0,...,No Deposit,NaN,NaN,0.0,Transient,62.00,0.0,2.0,Check-Out,2015-07-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119361,City Hotel,0.0,100.0,2017.0,August,35.0,31.0,1.0,3.0,2.0,...,No Deposit,16.0,NaN,0.0,Transient,95.85,0.0,0.0,Check-Out,2017-09-04
119362,City Hotel,0.0,198.0,2017.0,August,35.0,29.0,1.0,5.0,2.0,...,No Deposit,9.0,NaN,0.0,Transient,119.17,0.0,2.0,Check-Out,2017-09-04
119363,City Hotel,0.0,212.0,2017.0,August,35.0,28.0,2.0,5.0,2.0,...,No Deposit,7.0,NaN,0.0,Transient,92.17,0.0,1.0,Check-Out,2017-09-04
119364,City Hotel,0.0,212.0,2017.0,August,35.0,28.0,2.0,5.0,2.0,...,No Deposit,7.0,NaN,0.0,Transient,92.17,0.0,2.0,Check-Out,2017-09-04
119365,City Hotel,0.0,54.0,2017.0,August,35.0,27.0,3.0,5.0,1.0,...,No Deposit,14.0,NaN,0.0,Transient,266.75,0.0,1.0,Check-Out,2017-09-04
119366,City Hotel,0.0,210.0,2017.0,August,35.0,28.0,2.0,5.0,2.0,...,No Deposit,7.0,NaN,0.0,Transient,85.59,0.0,1.0,Check-Out,2017-09-04
119367,City Hotel,0.0,212.0,2017.0,August,35.0,28.0,2.0,5.0,2.0,...,No Deposit,7.0,NaN,0.0,Transient,85.59,0.0,0.0,Check-Out,2017-09-04
119368,City Hotel,0.0,261.0,2017.0,August,35.0,30.0,1.0,4.0,2.0,...,No Deposit,14.0,NaN,0.0,Transient,99.00,0.0,0.0,Check-Out,2017-09-04
119369,City Hotel,0.0,207.0,2017.0,August,34.0,25.0,3.0,7.0,2.0,...,No Deposit,14.0,NaN,0.0,Transient,96.25,0.0,2.0,Check-Out,2017-09-04
119370,City Hotel,0.0,201.0,2017.0,August,35.0,30.0,1.0,4.0,1.0,...,No Deposit,9.0,NaN,0.0,Transient,108.00,0.0,2.0,Check-Out,2017-09-04
119371,City Hotel,0.0,175.0,2017.0,August,35.0,31.0,1.0,3.0,2.0,...,No Deposit,42.0,NaN,0.0,Transient,86.85,0.0,2.0,Check-Out,2017-09-04
119372,City Hotel,0.0,175.0,2017.0,August,35.0,31.0,1.0,3.0,1.0,...,No Deposit,42.0,NaN,0.0,Transient,82.35,0.0,1.0,Check-Out,2017-09-04
119373,City Hotel,0.0,175.0,2017.0,August,35.0,31.0,1.0,3.0,1.0,...,No Deposit,42.0,NaN,0.0,Transient,82.35,0.0,1.0,Check-Out,2017-09-04
119374,City Hotel,0.0,201.0,2017.0,August,35.0,29.0,1.0,5.0,2.0,...,No Deposit,9.0,NaN,0.0,Transient,117.00,0.0,2.0,Check-Out,2017-09-04
119375,City Hotel,0.0,200.0,2017.0,August,35.0,30.0,1.0,4.0,2.0,...,No Deposit,16.0,NaN,0.0,Transient,85.50,0.0,1.0,Check-Out,2017-09-04
119376,City Hotel,0.0,165.0,2017.0,August,35.0,29.0,1.0,5.0,3.0,...,No Deposit,9.0,NaN,0.0,Transient,209.25,0.0,3.0,Check-Out,2017-09-04
119377,City Hotel,0.0,185.0,2017.0,August,35.0,30.0,1.0,4.0,2.0,...,No Deposit,9.0,NaN,0.0,Transient,99.00,0.0,1.0,Check-Out,2017-09-04
119378,City Hotel,0.0,247.0,2017.0,August,35.0,31.0,1.0,3.0,2.0,...,No Deposit,42.0,NaN,0.0,Transient,86.85,0.0,0.0,Check-Out,2017-09-04
119379,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,1.0,3.0,2.0,...,No Deposit,9.0,NaN,0.0,Transient,155.00,0.0,1.0,Check-Out,2017-09-04
119380,City Hotel,0.0,44.0,2017.0,August,35.0,31.0,1.0,3.0,2.0,...,No Deposit,9.0,NaN,0.0,Transient,140.75,0.0,1.0,Check-Out,2017-09-04
119381,City Hotel,0.0,188.0,2017.0,August,35.0,31.0,2.0,3.0,2.0,...,No Deposit,14.0,NaN,0.0,Transient,99.00,0.0,0.0,Check-Out,2017-09-05
119382,City Hotel,0.0,135.0,2017.0,August,35.0,30.0,2.0,4.0,3.0,...,No Deposit,7.0,NaN,0.0,Transient,209.00,0.0,0.0,Check-Out,2017-09-05
119383,City Hotel,0.0,164.0,2017.0,August,35.0,31.0,2.0,4.0,2.0,...,No Deposit,42.0,NaN,0.0,Transient,87.60,0.0,0.0,Check-Out,2017-09-06
119384,City Hotel,0.0,21.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,...,No Deposit,394.0,NaN,0.0,Transient,96.14,0.0,2.0,Check-Out,2017-09-06
119385,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,...,No Deposit,394.0,NaN,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06
119386,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,...,No Deposit,9.0,NaN,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07
119387,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,...,No Deposit,9.0,NaN,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07
119388,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,...,No Deposit,89.0,NaN,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07
119389,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,...,No Deposit,9.0,NaN,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07
119390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
# 随机采样
data.sample(n=5, random_state=101)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
54215,City Hotel,1,74,2016,July,28,9,0,1,2,...,No Deposit,9.0,NaN,0,Transient,127.8,0,0,Canceled,2016-04-28
42638,City Hotel,0,22,2015,September,37,8,0,1,2,...,No Deposit,8.0,NaN,0,Transient,120.0,0,1,Check-Out,2015-09-09
8295,Resort Hotel,1,197,2016,September,39,21,2,5,2,...,Non Refund,253.0,NaN,0,Transient,66.6,0,0,Canceled,2016-03-31
82129,City Hotel,1,99,2016,February,8,19,0,1,2,...,No Deposit,NaN,67.0,0,Transient-Party,80.0,0,0,Canceled,2015-12-22
8493,Resort Hotel,1,157,2016,October,40,1,2,2,2,...,Non Refund,96.0,NaN,0,Transient,52.0,0,0,Canceled,2016-05-09

In [44]:
# 创建一列新数据
data.loc[:, 'tags'] = data['adults'] + data['children']
data.loc[:, 'tags']

0         2.0
1         2.0
2         1.0
3         1.0
4         2.0
5         2.0
6         2.0
7         2.0
8         2.0
9         2.0
10        2.0
11        2.0
12        2.0
13        3.0
14        2.0
15        2.0
16        2.0
17        2.0
18        2.0
19        2.0
20        1.0
21        2.0
22        2.0
23        2.0
24        2.0
25        2.0
26        2.0
27        2.0
28        2.0
29        2.0
         ...
119360    2.0
119361    2.0
119362    2.0
119363    2.0
119364    2.0
119365    1.0
119366    2.0
119367    2.0
119368    2.0
119369    2.0
119370    1.0
119371    2.0
119372    1.0
119373    1.0
119374    2.0
119375    2.0
119376    3.0
119377    2.0
119378    2.0
119379    2.0
119380    2.0
119381    2.0
119382    3.0
119383    2.0
119384    2.0
119385    2.0
119386    3.0
119387    2.0
119388    2.0
119389    2.0
Name: tags, Length: 119390, dtype: float64

In [47]:
# .at 和 .iat 可以迅速找到数据
data.at[5,'adults']

2

In [49]:
# 布尔索引
data[(data['adults'] > 2) | (data['children'] >4)]  # 条件之间的括号是必须的，否则这里断句会出现问题导致报错

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,tags
34,Resort Hotel,1,45,2015,July,27,2,1,3,3,...,241.0,NaN,0,Transient,108.80,0,1,Canceled,2015-05-19,3.0
35,Resort Hotel,1,40,2015,July,27,2,1,3,3,...,241.0,NaN,0,Transient,108.80,0,1,Canceled,2015-06-19,3.0
37,Resort Hotel,0,36,2015,July,27,2,1,3,3,...,241.0,NaN,0,Transient,108.80,0,1,Check-Out,2015-07-06,3.0
38,Resort Hotel,1,43,2015,July,27,2,1,3,3,...,241.0,NaN,0,Transient,108.80,0,0,Canceled,2015-05-23,3.0
68,Resort Hotel,1,71,2015,July,27,3,0,2,3,...,242.0,NaN,0,Transient,110.30,0,2,Canceled,2015-06-16,3.0
74,Resort Hotel,1,51,2015,July,27,3,0,2,3,...,242.0,NaN,0,Transient,110.30,0,0,Canceled,2015-06-09,3.0
79,Resort Hotel,0,81,2015,July,27,3,2,6,3,...,5.0,NaN,0,Transient,85.86,0,0,Check-Out,2015-07-11,3.0
97,Resort Hotel,0,63,2015,July,27,3,2,5,3,...,105.0,NaN,0,Transient,196.54,0,1,Check-Out,2015-07-10,3.0
106,Resort Hotel,1,73,2015,July,27,4,2,5,3,...,250.0,NaN,0,Transient,172.00,0,1,Canceled,2015-05-20,3.0
113,Resort Hotel,0,29,2015,July,27,4,2,6,3,...,241.0,NaN,0,Transient,116.50,0,1,Check-Out,2015-07-12,3.0
125,Resort Hotel,0,32,2015,July,27,4,0,1,4,...,NaN,NaN,0,Transient,0.00,0,1,Check-Out,2015-07-05,4.0
140,Resort Hotel,0,44,2015,July,28,5,2,0,3,...,240.0,NaN,0,Transient,225.00,2,0,Check-Out,2015-07-07,3.0
156,Resort Hotel,0,94,2015,July,28,5,4,6,3,...,NaN,NaN,0,Transient,124.45,1,1,Check-Out,2015-07-15,3.0
163,Resort Hotel,0,94,2015,July,28,6,1,3,3,...,96.0,NaN,0,Transient,171.32,0,1,Check-Out,2015-07-10,3.0
166,Resort Hotel,0,51,2015,July,28,6,1,3,3,...,241.0,NaN,0,Transient,117.81,0,2,Check-Out,2015-07-10,3.0
199,Resort Hotel,0,0,2015,July,28,7,0,1,3,...,NaN,NaN,0,Transient,195.00,1,0,Check-Out,2015-07-08,3.0
201,Resort Hotel,0,8,2015,July,28,7,0,4,3,...,240.0,NaN,0,Transient,193.00,0,1,Check-Out,2015-07-11,5.0
203,Resort Hotel,0,88,2015,July,28,7,0,4,3,...,95.0,NaN,0,Transient,150.00,0,1,Check-Out,2015-07-11,3.0
227,Resort Hotel,0,82,2015,July,28,8,2,6,3,...,250.0,NaN,0,Transient,112.00,0,1,Check-Out,2015-07-16,3.0
228,Resort Hotel,0,100,2015,July,28,8,2,7,3,...,240.0,NaN,0,Transient-Party,130.10,0,3,Check-Out,2015-07-17,3.0
231,Resort Hotel,0,68,2015,July,28,9,0,2,3,...,250.0,NaN,0,Transient,124.00,1,1,Check-Out,2015-07-11,3.0
273,Resort Hotel,0,11,2015,July,28,10,2,6,3,...,250.0,NaN,0,Transient,159.75,1,0,Check-Out,2015-07-18,4.0
284,Resort Hotel,0,117,2015,July,28,11,2,4,3,...,15.0,NaN,0,Transient,144.40,0,1,Check-Out,2015-07-17,3.0
315,Resort Hotel,1,58,2015,July,29,12,2,5,3,...,250.0,NaN,0,Transient,164.57,0,1,Canceled,2015-06-29,4.0
328,Resort Hotel,1,55,2015,July,29,12,4,10,2,...,8.0,NaN,0,Contract,133.16,0,1,No-Show,2015-07-12,12.0
354,Resort Hotel,0,0,2015,July,29,13,1,1,4,...,NaN,NaN,0,Transient,150.00,0,0,Check-Out,2015-07-15,4.0
373,Resort Hotel,0,109,2015,July,29,13,1,4,3,...,NaN,NaN,0,Transient,163.80,0,1,Check-Out,2015-07-18,3.0
406,Resort Hotel,0,113,2015,July,29,14,4,11,3,...,NaN,NaN,0,Transient,187.50,1,3,Check-Out,2015-07-29,3.0
423,Resort Hotel,0,57,2015,July,29,15,0,2,3,...,305.0,NaN,0,Transient-Party,148.23,0,0,Check-Out,2015-07-17,3.0
427,Resort Hotel,0,57,2015,July,29,15,0,2,3,...,305.0,NaN,0,Transient-Party,148.23,0,0,Check-Out,2015-07-17,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119128,City Hotel,0,209,2017,August,34,26,2,2,3,...,9.0,NaN,0,Transient,162.00,0,0,Check-Out,2017-08-30,3.0
119131,City Hotel,0,146,2017,August,35,28,1,1,3,...,9.0,NaN,0,Transient,195.00,0,1,Check-Out,2017-08-30,3.0
119135,City Hotel,0,4,2017,August,35,28,1,1,3,...,9.0,NaN,0,Transient,219.00,0,2,Check-Out,2017-08-30,3.0
119136,City Hotel,0,223,2017,August,34,23,2,5,3,...,83.0,NaN,0,Transient,154.70,0,1,Check-Out,2017-08-30,3.0
119139,City Hotel,0,6,2017,August,35,27,2,1,3,...,9.0,NaN,0,Transient,196.33,0,2,Check-Out,2017-08-30,3.0
119140,City Hotel,0,52,2017,August,35,27,2,1,3,...,9.0,NaN,0,Transient,258.00,1,2,Check-Out,2017-08-30,3.0
119141,City Hotel,0,190,2017,August,35,27,2,1,3,...,9.0,NaN,0,Transient,162.00,0,2,Check-Out,2017-08-30,3.0
119155,City Hotel,0,214,2017,August,35,27,2,2,3,...,28.0,NaN,0,Transient,115.00,0,0,Check-Out,2017-08-31,3.0
119158,City Hotel,0,180,2017,August,34,25,2,4,3,...,9.0,NaN,0,Transient,222.30,1,0,Check-Out,2017-08-31,3.0
119168,City Hotel,0,232,2017,August,34,26,2,3,3,...,9.0,NaN,0,Transient,157.25,0,0,Check-Out,2017-08-31,3.0
119172,City Hotel,0,147,2017,August,34,24,2,5,3,...,85.0,NaN,0,Transient,140.40,0,0,Check-Out,2017-08-31,3.0
119233,City Hotel,0,28,2017,August,35,30,0,2,3,...,9.0,NaN,0,Transient,210.00,0,0,Check-Out,2017-09-01,3.0
119242,City Hotel,0,211,2017,August,35,28,1,3,3,...,14.0,NaN,0,Transient,161.50,0,1,Check-Out,2017-09-01,3.0
119280,City Hotel,0,30,2017,August,35,30,0,3,3,...,7.0,NaN,0,Transient,195.47,0,3,Check-Out,2017-09-02,3.0
119288,City Hotel,0,44,2017,August,35,30,0,3,3,...,9.0,NaN,0,Transient,206.33,0,1,Check-Out,2017-09-02,3.0
119289,City Hotel,0,25,2017,August,35,30,0,3,3,...,9.0,NaN,0,Transient,236.33,0,3,Check-Out,2017-09-02,3.0
119299,City Hotel,0,26,2017,August,35,29,0,4,3,...,9.0,NaN,0,Transient,207.25,0,0,Check-Out,2017-09-02,3.0
119313,City Hotel,0,211,2017,August,35,31,0,3,3,...,9.0,NaN,0,Transient,162.00,0,1,Check-Out,2017-09-03,3.0
119317,City Hotel,0,188,2017,August,35,30,0,4,3,...,15.0,NaN,0,Transient,129.60,0,0,Check-Out,2017-09-03,3.0
119335,City Hotel,0,63,2017,August,35,31,0,3,3,...,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03,3.0
119339,City Hotel,0,110,2017,August,35,29,0,5,3,...,14.0,NaN,0,Transient,229.00,0,1,Check-Out,2017-09-03,3.0
119342,City Hotel,0,63,2017,August,35,31,0,3,3,...,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03,3.0
119347,City Hotel,0,63,2017,August,35,31,0,3,3,...,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03,3.0
119348,City Hotel,0,63,2017,August,35,31,0,3,3,...,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03,3.0
119352,City Hotel,0,63,2017,August,35,31,0,3,3,...,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03,3.0
119353,City Hotel,0,63,2017,August,35,31,0,3,3,...,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03,3.0
119354,City Hotel,0,63,2017,August,35,31,0,3,3,...,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03,3.0
119376,City Hotel,0,165,2017,August,35,29,1,5,3,...,9.0,NaN,0,Transient,209.25,0,3,Check-Out,2017-09-04,3.0
119382,City Hotel,0,135,2017,August,35,30,2,4,3,...,7.0,NaN,0,Transient,209.00,0,0,Check-Out,2017-09-05,3.0
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07,3.0

In [52]:
data[(data['adults'] > 1) & (data['children'] >3)]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,tags
328,Resort Hotel,1,55,2015,July,29,12,4,10,2,...,8.0,NaN,0,Contract,133.16,0,1,No-Show,2015-07-12,12.0

In [54]:
data[~(data['children'] > 2)]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,tags
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,2.0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,2.0
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,1.0
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,1.0
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03,2.0
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03,2.0
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,NaN,NaN,0,Transient,107.00,0,0,Check-Out,2015-07-03,2.0
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,303.0,NaN,0,Transient,103.00,0,1,Check-Out,2015-07-03,2.0
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,240.0,NaN,0,Transient,82.00,0,1,Canceled,2015-05-06,2.0
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,15.0,NaN,0,Transient,105.50,0,0,Canceled,2015-04-22,2.0
10,Resort Hotel,1,23,2015,July,27,1,0,4,2,...,240.0,NaN,0,Transient,123.00,0,0,Canceled,2015-06-23,2.0
11,Resort Hotel,0,35,2015,July,27,1,0,4,2,...,240.0,NaN,0,Transient,145.00,0,0,Check-Out,2015-07-05,2.0
12,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,240.0,NaN,0,Transient,97.00,0,3,Check-Out,2015-07-05,2.0
13,Resort Hotel,0,18,2015,July,27,1,0,4,2,...,241.0,NaN,0,Transient,154.77,0,1,Check-Out,2015-07-05,3.0
14,Resort Hotel,0,37,2015,July,27,1,0,4,2,...,241.0,NaN,0,Transient,94.71,0,0,Check-Out,2015-07-05,2.0
15,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,240.0,NaN,0,Transient,97.00,0,3,Check-Out,2015-07-05,2.0
16,Resort Hotel,0,37,2015,July,27,1,0,4,2,...,8.0,NaN,0,Contract,97.50,0,0,Check-Out,2015-07-05,2.0
17,Resort Hotel,0,12,2015,July,27,1,0,1,2,...,240.0,NaN,0,Transient,88.20,0,0,Check-Out,2015-07-02,2.0
18,Resort Hotel,0,0,2015,July,27,1,0,1,2,...,NaN,110.0,0,Transient,107.42,0,0,Check-Out,2015-07-02,2.0
19,Resort Hotel,0,7,2015,July,27,1,0,4,2,...,250.0,NaN,0,Transient,153.00,0,1,Check-Out,2015-07-05,2.0
20,Resort Hotel,0,37,2015,July,27,1,1,4,1,...,241.0,NaN,0,Transient,97.29,0,1,Check-Out,2015-07-06,1.0
21,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07,2.0
22,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07,2.0
23,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,250.0,NaN,0,Transient,99.67,0,1,Check-Out,2015-07-07,2.0
24,Resort Hotel,0,127,2015,July,27,1,2,5,2,...,115.0,NaN,0,Contract,94.95,0,1,Check-Out,2015-07-01,2.0
25,Resort Hotel,0,78,2015,July,27,1,2,5,2,...,5.0,NaN,0,Transient,63.60,1,0,Check-Out,2015-07-08,2.0
26,Resort Hotel,0,48,2015,July,27,1,2,5,2,...,8.0,NaN,0,Contract,79.50,0,0,Check-Out,2015-07-08,2.0
27,Resort Hotel,1,60,2015,July,27,1,2,5,2,...,240.0,NaN,0,Transient,107.00,0,2,Canceled,2015-05-11,2.0
28,Resort Hotel,0,77,2015,July,27,1,2,5,2,...,240.0,NaN,0,Transient,94.00,0,0,Check-Out,2015-07-08,2.0
29,Resort Hotel,0,99,2015,July,27,1,2,5,2,...,240.0,NaN,0,Transient,87.30,1,1,Check-Out,2015-07-08,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119360,City Hotel,0,195,2017,August,35,29,1,5,2,...,9.0,NaN,0,Transient,117.00,0,1,Check-Out,2017-09-04,2.0
119361,City Hotel,0,100,2017,August,35,31,1,3,2,...,16.0,NaN,0,Transient,95.85,0,0,Check-Out,2017-09-04,2.0
119362,City Hotel,0,198,2017,August,35,29,1,5,2,...,9.0,NaN,0,Transient,119.17,0,2,Check-Out,2017-09-04,2.0
119363,City Hotel,0,212,2017,August,35,28,2,5,2,...,7.0,NaN,0,Transient,92.17,0,1,Check-Out,2017-09-04,2.0
119364,City Hotel,0,212,2017,August,35,28,2,5,2,...,7.0,NaN,0,Transient,92.17,0,2,Check-Out,2017-09-04,2.0
119365,City Hotel,0,54,2017,August,35,27,3,5,1,...,14.0,NaN,0,Transient,266.75,0,1,Check-Out,2017-09-04,1.0
119366,City Hotel,0,210,2017,August,35,28,2,5,2,...,7.0,NaN,0,Transient,85.59,0,1,Check-Out,2017-09-04,2.0
119367,City Hotel,0,212,2017,August,35,28,2,5,2,...,7.0,NaN,0,Transient,85.59,0,0,Check-Out,2017-09-04,2.0
119368,City Hotel,0,261,2017,August,35,30,1,4,2,...,14.0,NaN,0,Transient,99.00,0,0,Check-Out,2017-09-04,2.0
119369,City Hotel,0,207,2017,August,34,25,3,7,2,...,14.0,NaN,0,Transient,96.25,0,2,Check-Out,2017-09-04,2.0
119370,City Hotel,0,201,2017,August,35,30,1,4,1,...,9.0,NaN,0,Transient,108.00,0,2,Check-Out,2017-09-04,1.0
119371,City Hotel,0,175,2017,August,35,31,1,3,2,...,42.0,NaN,0,Transient,86.85,0,2,Check-Out,2017-09-04,2.0
119372,City Hotel,0,175,2017,August,35,31,1,3,1,...,42.0,NaN,0,Transient,82.35,0,1,Check-Out,2017-09-04,1.0
119373,City Hotel,0,175,2017,August,35,31,1,3,1,...,42.0,NaN,0,Transient,82.35,0,1,Check-Out,2017-09-04,1.0
119374,City Hotel,0,201,2017,August,35,29,1,5,2,...,9.0,NaN,0,Transient,117.00,0,2,Check-Out,2017-09-04,2.0
119375,City Hotel,0,200,2017,August,35,30,1,4,2,...,16.0,NaN,0,Transient,85.50,0,1,Check-Out,2017-09-04,2.0
119376,City Hotel,0,165,2017,August,35,29,1,5,3,...,9.0,NaN,0,Transient,209.25,0,3,Check-Out,2017-09-04,3.0
119377,City Hotel,0,185,2017,August,35,30,1,4,2,...,9.0,NaN,0,Transient,99.00,0,1,Check-Out,2017-09-04,2.0
119378,City Hotel,0,247,2017,August,35,31,1,3,2,...,42.0,NaN,0,Transient,86.85,0,0,Check-Out,2017-09-04,2.0
119379,City Hotel,0,109,2017,August,35,31,1,3,2,...,9.0,NaN,0,Transient,155.00,0,1,Check-Out,2017-09-04,2.0
119380,City Hotel,0,44,2017,August,35,31,1,3,2,...,9.0,NaN,0,Transient,140.75,0,1,Check-Out,2017-09-04,2.0
119381,City Hotel,0,188,2017,August,35,31,2,3,2,...,14.0,NaN,0,Transient,99.00,0,0,Check-Out,2017-09-05,2.0
119382,City Hotel,0,135,2017,August,35,30,2,4,3,...,7.0,NaN,0,Transient,209.00,0,0,Check-Out,2017-09-05,3.0
119383,City Hotel,0,164,2017,August,35,31,2,4,2,...,42.0,NaN,0,Transient,87.60,0,0,Check-Out,2017-09-06,2.0
119384,City Hotel,0,21,2017,August,35,30,2,5,2,...,394.0,NaN,0,Transient,96.14,0,2,Check-Out,2017-09-06,2.0
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06,2.0
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07,3.0
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07,2.0
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07,2.0
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07,2.0

In [59]:
# .isin() 索引
data[data['distribution_channel'].isin(['Direct', 'Corporate'])]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,tags
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,2.0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,2.0
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,1.0
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,1.0
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,NaN,NaN,0,Transient,107.00,0,0,Check-Out,2015-07-03,2.0
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,303.0,NaN,0,Transient,103.00,0,1,Check-Out,2015-07-03,2.0
18,Resort Hotel,0,0,2015,July,27,1,0,1,2,...,NaN,110.0,0,Transient,107.42,0,0,Check-Out,2015-07-02,2.0
19,Resort Hotel,0,7,2015,July,27,1,0,4,2,...,250.0,NaN,0,Transient,153.00,0,1,Check-Out,2015-07-05,2.0
21,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07,2.0
22,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07,2.0
23,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,250.0,NaN,0,Transient,99.67,0,1,Check-Out,2015-07-07,2.0
30,Resort Hotel,0,118,2015,July,27,1,4,10,1,...,NaN,NaN,0,Transient,62.00,0,2,Check-Out,2015-07-15,1.0
32,Resort Hotel,1,96,2015,July,27,1,2,8,2,...,NaN,NaN,0,Transient,108.30,0,2,Canceled,2015-05-29,2.0
39,Resort Hotel,0,70,2015,July,27,2,2,3,2,...,250.0,NaN,0,Transient,137.00,0,1,Check-Out,2015-07-07,2.0
42,Resort Hotel,0,16,2015,July,27,2,2,3,2,...,NaN,NaN,0,Transient,123.00,0,0,Check-Out,2015-07-07,2.0
43,Resort Hotel,0,70,2015,July,27,2,2,3,2,...,250.0,NaN,0,Transient,137.00,0,1,Check-Out,2015-07-07,2.0
55,Resort Hotel,0,1,2015,July,27,2,0,1,2,...,NaN,NaN,0,Transient,107.00,1,2,Check-Out,2015-07-03,4.0
56,Resort Hotel,0,0,2015,July,27,2,0,1,2,...,NaN,NaN,0,Transient,147.00,0,0,Check-Out,2015-07-03,2.0
58,Resort Hotel,0,0,2015,July,27,2,0,1,2,...,NaN,NaN,0,Transient,123.00,0,0,Check-Out,2015-07-03,2.0
62,Resort Hotel,0,17,2015,July,27,2,0,3,2,...,250.0,NaN,0,Transient,133.00,0,1,Check-Out,2015-07-05,2.0
83,Resort Hotel,1,81,2015,July,27,3,3,7,2,...,250.0,NaN,0,Transient,124.00,0,1,Canceled,2015-06-09,2.0
99,Resort Hotel,0,102,2015,July,27,3,2,5,2,...,250.0,NaN,0,Transient,90.95,0,0,Check-Out,2015-07-10,2.0
100,Resort Hotel,0,4,2015,July,27,4,2,1,2,...,250.0,NaN,0,Transient,92.67,0,1,Check-Out,2015-07-07,2.0
106,Resort Hotel,1,73,2015,July,27,4,2,5,3,...,250.0,NaN,0,Transient,172.00,0,1,Canceled,2015-05-20,3.0
118,Resort Hotel,0,79,2015,July,27,4,4,6,2,...,250.0,NaN,0,Transient,149.00,0,1,Check-Out,2015-07-14,3.0
122,Resort Hotel,1,36,2015,July,27,4,0,1,1,...,250.0,NaN,0,Transient,123.00,0,0,No-Show,2015-07-04,1.0
125,Resort Hotel,0,32,2015,July,27,4,0,1,4,...,NaN,NaN,0,Transient,0.00,0,1,Check-Out,2015-07-05,4.0
139,Resort Hotel,0,2,2015,July,28,5,1,0,2,...,NaN,NaN,0,Transient,167.00,0,1,Check-Out,2015-07-06,2.0
150,Resort Hotel,0,97,2015,July,28,5,2,5,2,...,250.0,NaN,0,Transient,164.20,1,1,Check-Out,2015-07-12,4.0
156,Resort Hotel,0,94,2015,July,28,5,4,6,3,...,NaN,NaN,0,Transient,124.45,1,1,Check-Out,2015-07-15,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119198,City Hotel,0,27,2017,August,35,28,1,3,2,...,14.0,NaN,0,Transient,169.00,1,0,Check-Out,2017-09-01,2.0
119215,City Hotel,0,2,2017,August,35,31,0,1,1,...,NaN,NaN,0,Transient,140.00,0,2,Check-Out,2017-09-01,1.0
119224,City Hotel,0,83,2017,August,35,28,1,3,1,...,14.0,NaN,0,Transient,147.68,0,0,Check-Out,2017-09-01,1.0
119238,City Hotel,0,173,2017,August,35,28,1,3,2,...,14.0,NaN,0,Transient,135.00,0,2,Check-Out,2017-09-01,2.0
119242,City Hotel,0,211,2017,August,35,28,1,3,3,...,14.0,NaN,0,Transient,161.50,0,1,Check-Out,2017-09-01,3.0
119248,City Hotel,0,22,2017,August,35,29,0,3,1,...,NaN,485.0,0,Transient,75.00,0,4,Check-Out,2017-09-01,1.0
119254,City Hotel,0,9,2017,August,35,28,1,3,2,...,14.0,NaN,0,Transient,210.00,0,0,Check-Out,2017-09-01,4.0
119257,City Hotel,0,190,2017,August,35,28,1,3,2,...,14.0,NaN,0,Transient,99.00,0,2,Check-Out,2017-09-01,2.0
119261,City Hotel,0,239,2017,August,35,27,2,3,2,...,14.0,NaN,0,Transient,96.25,0,0,Check-Out,2017-09-01,2.0
119272,City Hotel,0,22,2017,August,35,28,1,3,2,...,14.0,NaN,0,Transient,160.00,0,0,Check-Out,2017-09-01,2.0
119284,City Hotel,0,141,2017,August,35,29,0,4,2,...,14.0,NaN,0,Transient,138.75,0,1,Check-Out,2017-09-02,2.0
119302,City Hotel,0,217,2017,August,35,28,1,4,2,...,14.0,NaN,0,Transient,99.00,0,0,Check-Out,2017-09-02,2.0
119304,City Hotel,0,4,2017,August,35,30,0,3,1,...,14.0,NaN,0,Transient,140.70,0,0,Check-Out,2017-09-02,1.0
119305,City Hotel,0,66,2017,August,35,30,0,3,1,...,14.0,NaN,0,Transient,141.90,0,0,Check-Out,2017-09-02,1.0
119308,City Hotel,0,138,2017,August,35,29,0,5,1,...,14.0,NaN,0,Transient,117.90,0,0,Check-Out,2017-09-03,1.0
119320,City Hotel,0,140,2017,August,35,29,0,5,2,...,14.0,NaN,0,Transient,156.00,0,1,Check-Out,2017-09-03,2.0
119324,City Hotel,0,8,2017,August,35,31,0,3,2,...,14.0,NaN,0,Transient,119.40,0,0,Check-Out,2017-09-03,2.0
119325,City Hotel,0,147,2017,August,35,28,1,5,2,...,14.0,NaN,0,Transient,117.00,0,1,Check-Out,2017-09-03,2.0
119329,City Hotel,0,30,2017,August,35,31,0,3,2,...,14.0,NaN,0,Transient,151.67,1,0,Check-Out,2017-09-03,2.0
119337,City Hotel,0,107,2017,August,35,30,0,4,2,...,14.0,NaN,0,Transient,146.40,0,0,Check-Out,2017-09-03,2.0
119339,City Hotel,0,110,2017,August,35,29,0,5,3,...,14.0,NaN,0,Transient,229.00,0,1,Check-Out,2017-09-03,3.0
119340,City Hotel,0,110,2017,August,35,29,0,5,2,...,14.0,NaN,0,Transient,171.00,0,2,Check-Out,2017-09-03,2.0
119351,City Hotel,0,72,2017,August,35,31,0,3,2,...,14.0,NaN,0,Transient,134.82,0,1,Check-Out,2017-09-03,2.0
119355,City Hotel,0,111,2017,August,35,29,1,5,1,...,14.0,NaN,0,Transient,135.00,0,2,Check-Out,2017-09-04,1.0
119356,City Hotel,0,111,2017,August,35,29,1,5,2,...,14.0,NaN,0,Transient,135.00,0,1,Check-Out,2017-09-04,2.0
119358,City Hotel,0,135,2017,August,35,30,1,4,2,...,14.0,NaN,0,Transient,143.10,0,1,Check-Out,2017-09-04,2.0
119365,City Hotel,0,54,2017,August,35,27,3,5,1,...,14.0,NaN,0,Transient,266.75,0,1,Check-Out,2017-09-04,1.0
119368,City Hotel,0,261,2017,August,35,30,1,4,2,...,14.0,NaN,0,Transient,99.00,0,0,Check-Out,2017-09-04,2.0
119369,City Hotel,0,207,2017,August,34,25,3,7,2,...,14.0,NaN,0,Transient,96.25,0,2,Check-Out,2017-09-04,2.0
119381,City Hotel,0,188,2017,August,35,31,2,3,2,...,14.0,NaN,0,Transient,99.00,0,0,Check-Out,2017-09-05,2.0

In [68]:
# where()
data['adults'].where(data['adults'] >= 2)

0         2.0
1         2.0
2         NaN
3         NaN
4         2.0
5         2.0
6         2.0
7         2.0
8         2.0
9         2.0
10        2.0
11        2.0
12        2.0
13        2.0
14        2.0
15        2.0
16        2.0
17        2.0
18        2.0
19        2.0
20        NaN
21        2.0
22        2.0
23        2.0
24        2.0
25        2.0
26        2.0
27        2.0
28        2.0
29        2.0
         ...
119360    2.0
119361    2.0
119362    2.0
119363    2.0
119364    2.0
119365    NaN
119366    2.0
119367    2.0
119368    2.0
119369    2.0
119370    NaN
119371    2.0
119372    NaN
119373    NaN
119374    2.0
119375    2.0
119376    3.0
119377    2.0
119378    2.0
119379    2.0
119380    2.0
119381    2.0
119382    3.0
119383    2.0
119384    2.0
119385    2.0
119386    3.0
119387    2.0
119388    2.0
119389    2.0
Name: adults, Length: 119390, dtype: float64

In [69]:
# mask
data['adults'].mask(data['adults'] >= 2)

0         NaN
1         NaN
2         1.0
3         1.0
4         NaN
5         NaN
6         NaN
7         NaN
8         NaN
9         NaN
10        NaN
11        NaN
12        NaN
13        NaN
14        NaN
15        NaN
16        NaN
17        NaN
18        NaN
19        NaN
20        1.0
21        NaN
22        NaN
23        NaN
24        NaN
25        NaN
26        NaN
27        NaN
28        NaN
29        NaN
         ...
119360    NaN
119361    NaN
119362    NaN
119363    NaN
119364    NaN
119365    1.0
119366    NaN
119367    NaN
119368    NaN
119369    NaN
119370    1.0
119371    NaN
119372    1.0
119373    1.0
119374    NaN
119375    NaN
119376    NaN
119377    NaN
119378    NaN
119379    NaN
119380    NaN
119381    NaN
119382    NaN
119383    NaN
119384    NaN
119385    NaN
119386    NaN
119387    NaN
119388    NaN
119389    NaN
Name: adults, Length: 119390, dtype: float64

In [71]:
# 利用 where() 和 mask() 对数据进行处理
data_where  = data.copy()
data_where['adults'] = data_where['adults'].where(data['adults'] >= 2, 2)
data_where['adults']

0         2
1         2
2         2
3         2
4         2
5         2
6         2
7         2
8         2
9         2
10        2
11        2
12        2
13        2
14        2
15        2
16        2
17        2
18        2
19        2
20        2
21        2
22        2
23        2
24        2
25        2
26        2
27        2
28        2
29        2
         ..
119360    2
119361    2
119362    2
119363    2
119364    2
119365    2
119366    2
119367    2
119368    2
119369    2
119370    2
119371    2
119372    2
119373    2
119374    2
119375    2
119376    3
119377    2
119378    2
119379    2
119380    2
119381    2
119382    3
119383    2
119384    2
119385    2
119386    3
119387    2
119388    2
119389    2
Name: adults, Length: 119390, dtype: int64

In [72]:
data_mask  = data.copy()
data_mask['adults'] = data_mask['adults'].mask(data['adults'] >= 2, 2)
data_mask['adults']

0         2
1         2
2         1
3         1
4         2
5         2
6         2
7         2
8         2
9         2
10        2
11        2
12        2
13        2
14        2
15        2
16        2
17        2
18        2
19        2
20        1
21        2
22        2
23        2
24        2
25        2
26        2
27        2
28        2
29        2
         ..
119360    2
119361    2
119362    2
119363    2
119364    2
119365    1
119366    2
119367    2
119368    2
119369    2
119370    1
119371    2
119372    1
119373    1
119374    2
119375    2
119376    2
119377    2
119378    2
119379    2
119380    2
119381    2
119382    2
119383    2
119384    2
119385    2
119386    2
119387    2
119388    2
119389    2
Name: adults, Length: 119390, dtype: int64

In [74]:
# query() 方法
data.query('adults >=2 and children == 2')

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,tags
45,Resort Hotel,1,47,2015,July,27,2,2,5,2,...,240.0,NaN,0,Transient,153.00,0,0,Canceled,2015-06-02,4.0
55,Resort Hotel,0,1,2015,July,27,2,0,1,2,...,NaN,NaN,0,Transient,107.00,1,2,Check-Out,2015-07-03,4.0
65,Resort Hotel,0,10,2015,July,27,3,0,2,2,...,240.0,NaN,0,Transient,153.00,1,0,Check-Out,2015-07-05,4.0
105,Resort Hotel,1,26,2015,July,27,4,2,5,2,...,240.0,NaN,0,Transient,163.00,0,0,Canceled,2015-06-09,4.0
119,Resort Hotel,0,2,2015,July,27,4,0,1,2,...,240.0,NaN,0,Transient,163.00,1,0,Check-Out,2015-07-05,4.0
148,Resort Hotel,1,34,2015,July,28,5,2,4,2,...,240.0,NaN,0,Transient,163.00,0,0,Canceled,2015-06-17,4.0
150,Resort Hotel,0,97,2015,July,28,5,2,5,2,...,250.0,NaN,0,Transient,164.20,1,1,Check-Out,2015-07-12,4.0
154,Resort Hotel,0,8,2015,July,28,5,4,5,2,...,240.0,NaN,0,Transient,175.00,1,1,Check-Out,2015-07-14,4.0
160,Resort Hotel,0,115,2015,July,28,6,1,4,2,...,240.0,NaN,0,Transient,167.00,0,0,Check-Out,2015-07-11,4.0
164,Resort Hotel,0,81,2015,July,28,6,1,3,2,...,250.0,NaN,0,Transient,210.00,1,0,Check-Out,2015-07-10,4.0
180,Resort Hotel,0,68,2015,July,28,6,2,5,2,...,240.0,NaN,0,Transient,185.00,0,0,Check-Out,2015-07-13,4.0
201,Resort Hotel,0,8,2015,July,28,7,0,4,3,...,240.0,NaN,0,Transient,193.00,0,1,Check-Out,2015-07-11,5.0
230,Resort Hotel,0,17,2015,July,28,9,0,1,2,...,242.0,NaN,0,Transient,123.00,0,3,Check-Out,2015-07-10,4.0
232,Resort Hotel,0,12,2015,July,28,9,0,2,2,...,NaN,NaN,0,Transient,146.00,1,0,Check-Out,2015-07-11,4.0
234,Resort Hotel,1,24,2015,July,28,9,0,3,2,...,242.0,NaN,0,Transient,123.00,0,1,Canceled,2015-06-16,4.0
235,Resort Hotel,1,44,2015,July,28,9,0,3,2,...,240.0,NaN,0,Transient,153.00,0,0,Canceled,2015-06-16,4.0
265,Resort Hotel,0,35,2015,July,28,10,2,3,2,...,240.0,NaN,0,Transient,149.40,0,0,Check-Out,2015-07-15,4.0
303,Resort Hotel,0,79,2015,July,28,11,2,6,2,...,250.0,NaN,0,Transient,213.75,0,0,Check-Out,2015-07-19,4.0
307,Resort Hotel,0,53,2015,July,29,12,1,0,2,...,240.0,NaN,0,Transient,153.00,1,0,Check-Out,2015-07-13,4.0
331,Resort Hotel,0,34,2015,July,29,12,2,0,2,...,240.0,NaN,0,Transient,193.00,0,1,Check-Out,2015-07-14,4.0
341,Resort Hotel,0,100,2015,July,29,12,2,2,2,...,250.0,NaN,0,Transient,130.05,1,1,Check-Out,2015-07-16,4.0
344,Resort Hotel,0,8,2015,July,29,12,2,3,2,...,240.0,NaN,0,Transient,196.00,0,1,Check-Out,2015-07-17,4.0
396,Resort Hotel,0,317,2015,July,29,14,1,5,2,...,240.0,NaN,0,Transient,230.67,1,2,Check-Out,2015-07-20,4.0
412,Resort Hotel,0,37,2015,July,29,15,2,6,2,...,240.0,NaN,0,Transient,216.13,1,0,Check-Out,2015-07-23,4.0
418,Resort Hotel,0,83,2015,July,29,15,2,7,2,...,240.0,NaN,0,Transient,190.33,0,1,Check-Out,2015-07-24,4.0
434,Resort Hotel,1,66,2015,July,29,16,0,2,2,...,240.0,NaN,0,Transient,195.00,0,1,Canceled,2015-07-02,4.0
439,Resort Hotel,0,7,2015,July,29,16,0,1,2,...,242.0,NaN,0,Transient,169.00,1,1,Check-Out,2015-07-17,4.0
440,Resort Hotel,0,0,2015,July,29,16,0,2,2,...,NaN,NaN,0,Transient,198.00,1,0,Check-Out,2015-07-18,4.0
484,Resort Hotel,0,23,2015,July,29,17,2,5,2,...,250.0,NaN,0,Transient,195.00,0,0,Check-Out,2015-07-24,4.0
486,Resort Hotel,1,23,2015,July,29,17,2,5,2,...,250.0,NaN,0,Transient,195.00,0,0,Canceled,2015-06-24,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118661,City Hotel,0,227,2017,August,33,18,2,4,2,...,9.0,NaN,0,Transient,199.77,0,1,Check-Out,2017-08-24,4.0
118675,City Hotel,0,163,2017,August,34,21,1,2,2,...,14.0,NaN,0,Transient,240.00,0,1,Check-Out,2017-08-24,4.0
118681,City Hotel,0,150,2017,August,34,21,1,2,2,...,83.0,NaN,0,Transient,188.00,0,1,Check-Out,2017-08-24,4.0
118754,City Hotel,0,182,2017,August,34,22,0,3,2,...,159.0,NaN,0,Transient,173.73,0,1,Check-Out,2017-08-25,4.0
118759,City Hotel,0,263,2017,August,34,22,0,3,2,...,83.0,NaN,0,Transient,168.00,0,1,Check-Out,2017-08-25,4.0
118783,City Hotel,0,177,2017,August,34,23,0,2,2,...,14.0,NaN,0,Transient,230.00,0,0,Check-Out,2017-08-25,4.0
118804,City Hotel,0,186,2017,August,33,19,2,5,2,...,9.0,NaN,0,Transient,218.43,0,0,Check-Out,2017-08-26,4.0
118832,City Hotel,0,163,2017,August,34,23,0,3,2,...,14.0,NaN,0,Transient,200.00,0,1,Check-Out,2017-08-26,4.0
118845,City Hotel,0,215,2017,August,34,25,0,1,2,...,14.0,NaN,0,Transient,215.00,0,0,Check-Out,2017-08-26,4.0
118906,City Hotel,0,224,2017,August,34,24,0,3,2,...,14.0,NaN,0,Transient,163.50,0,3,Check-Out,2017-08-27,4.0
118913,City Hotel,0,200,2017,August,34,25,0,2,3,...,NaN,NaN,0,Transient,294.00,1,0,Check-Out,2017-08-27,5.0
118920,City Hotel,0,131,2017,August,34,25,0,2,2,...,9.0,NaN,0,Transient,244.00,0,0,Check-Out,2017-08-27,4.0
118957,City Hotel,0,112,2017,August,34,25,0,2,2,...,9.0,NaN,0,Transient,235.00,0,0,Check-Out,2017-08-27,4.0
118958,City Hotel,0,0,2017,August,34,26,0,1,2,...,NaN,NaN,0,Transient,200.00,0,0,Check-Out,2017-08-27,4.0
118976,City Hotel,0,218,2017,August,33,18,3,7,2,...,14.0,NaN,0,Transient,215.86,0,1,Check-Out,2017-08-28,4.0
119031,City Hotel,0,164,2017,August,34,24,1,3,2,...,9.0,NaN,0,Transient,235.00,0,0,Check-Out,2017-08-28,4.0
119052,City Hotel,0,35,2017,August,34,26,2,1,2,...,14.0,NaN,0,Transient,176.64,0,1,Check-Out,2017-08-29,4.0
119058,City Hotel,0,301,2017,August,35,27,2,0,2,...,9.0,NaN,0,Transient,179.10,0,0,Check-Out,2017-08-29,4.0
119077,City Hotel,0,221,2017,August,34,26,2,1,2,...,9.0,NaN,0,Transient,198.00,0,1,Check-Out,2017-08-29,4.0
119126,City Hotel,0,130,2017,August,34,23,2,5,2,...,14.0,NaN,0,Transient,300.00,0,1,Check-Out,2017-08-30,4.0
119144,City Hotel,0,5,2017,August,35,29,0,1,2,...,9.0,NaN,0,Transient,259.00,0,0,Check-Out,2017-08-30,4.0
119151,City Hotel,0,0,2017,August,35,29,0,1,2,...,NaN,NaN,0,Transient,270.00,0,0,Check-Out,2017-08-30,4.0
119152,City Hotel,0,29,2017,August,35,27,2,1,2,...,9.0,NaN,0,Transient,233.00,0,0,Check-Out,2017-08-30,4.0
119153,City Hotel,0,22,2017,August,35,30,0,3,2,...,9.0,NaN,0,Transient,61.80,0,0,Check-Out,2017-09-02,4.0
119223,City Hotel,0,6,2017,August,35,28,1,3,2,...,7.0,NaN,0,Transient,190.00,0,1,Check-Out,2017-09-01,4.0
119247,City Hotel,0,140,2017,August,35,27,2,3,2,...,9.0,NaN,0,Transient,235.00,0,0,Check-Out,2017-09-01,4.0
119251,City Hotel,0,140,2017,August,35,27,2,3,2,...,9.0,NaN,0,Transient,235.00,0,0,Check-Out,2017-09-01,4.0
119254,City Hotel,0,9,2017,August,35,28,1,3,2,...,14.0,NaN,0,Transient,210.00,0,0,Check-Out,2017-09-01,4.0
119293,City Hotel,0,243,2017,August,35,30,0,3,2,...,9.0,NaN,0,Transient,189.00,0,3,Check-Out,2017-09-02,4.0
119319,City Hotel,0,45,2017,August,35,28,1,5,2,...,7.0,NaN,0,Transient,194.13,0,1,Check-Out,2017-09-03,4.0

In [76]:
data.query('adults <= children')

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,tags
45,Resort Hotel,1,47,2015,July,27,2,2,5,2,...,240.0,NaN,0,Transient,153.00,0,0,Canceled,2015-06-02,4.0
55,Resort Hotel,0,1,2015,July,27,2,0,1,2,...,NaN,NaN,0,Transient,107.00,1,2,Check-Out,2015-07-03,4.0
65,Resort Hotel,0,10,2015,July,27,3,0,2,2,...,240.0,NaN,0,Transient,153.00,1,0,Check-Out,2015-07-05,4.0
102,Resort Hotel,0,92,2015,July,27,4,2,4,1,...,241.0,NaN,0,Transient,96.49,0,2,Check-Out,2015-07-10,3.0
105,Resort Hotel,1,26,2015,July,27,4,2,5,2,...,240.0,NaN,0,Transient,163.00,0,0,Canceled,2015-06-09,4.0
119,Resort Hotel,0,2,2015,July,27,4,0,1,2,...,240.0,NaN,0,Transient,163.00,1,0,Check-Out,2015-07-05,4.0
148,Resort Hotel,1,34,2015,July,28,5,2,4,2,...,240.0,NaN,0,Transient,163.00,0,0,Canceled,2015-06-17,4.0
150,Resort Hotel,0,97,2015,July,28,5,2,5,2,...,250.0,NaN,0,Transient,164.20,1,1,Check-Out,2015-07-12,4.0
154,Resort Hotel,0,8,2015,July,28,5,4,5,2,...,240.0,NaN,0,Transient,175.00,1,1,Check-Out,2015-07-14,4.0
160,Resort Hotel,0,115,2015,July,28,6,1,4,2,...,240.0,NaN,0,Transient,167.00,0,0,Check-Out,2015-07-11,4.0
164,Resort Hotel,0,81,2015,July,28,6,1,3,2,...,250.0,NaN,0,Transient,210.00,1,0,Check-Out,2015-07-10,4.0
180,Resort Hotel,0,68,2015,July,28,6,2,5,2,...,240.0,NaN,0,Transient,185.00,0,0,Check-Out,2015-07-13,4.0
230,Resort Hotel,0,17,2015,July,28,9,0,1,2,...,242.0,NaN,0,Transient,123.00,0,3,Check-Out,2015-07-10,4.0
232,Resort Hotel,0,12,2015,July,28,9,0,2,2,...,NaN,NaN,0,Transient,146.00,1,0,Check-Out,2015-07-11,4.0
234,Resort Hotel,1,24,2015,July,28,9,0,3,2,...,242.0,NaN,0,Transient,123.00,0,1,Canceled,2015-06-16,4.0
235,Resort Hotel,1,44,2015,July,28,9,0,3,2,...,240.0,NaN,0,Transient,153.00,0,0,Canceled,2015-06-16,4.0
265,Resort Hotel,0,35,2015,July,28,10,2,3,2,...,240.0,NaN,0,Transient,149.40,0,0,Check-Out,2015-07-15,4.0
303,Resort Hotel,0,79,2015,July,28,11,2,6,2,...,250.0,NaN,0,Transient,213.75,0,0,Check-Out,2015-07-19,4.0
307,Resort Hotel,0,53,2015,July,29,12,1,0,2,...,240.0,NaN,0,Transient,153.00,1,0,Check-Out,2015-07-13,4.0
328,Resort Hotel,1,55,2015,July,29,12,4,10,2,...,8.0,NaN,0,Contract,133.16,0,1,No-Show,2015-07-12,12.0
331,Resort Hotel,0,34,2015,July,29,12,2,0,2,...,240.0,NaN,0,Transient,193.00,0,1,Check-Out,2015-07-14,4.0
341,Resort Hotel,0,100,2015,July,29,12,2,2,2,...,250.0,NaN,0,Transient,130.05,1,1,Check-Out,2015-07-16,4.0
344,Resort Hotel,0,8,2015,July,29,12,2,3,2,...,240.0,NaN,0,Transient,196.00,0,1,Check-Out,2015-07-17,4.0
396,Resort Hotel,0,317,2015,July,29,14,1,5,2,...,240.0,NaN,0,Transient,230.67,1,2,Check-Out,2015-07-20,4.0
412,Resort Hotel,0,37,2015,July,29,15,2,6,2,...,240.0,NaN,0,Transient,216.13,1,0,Check-Out,2015-07-23,4.0
418,Resort Hotel,0,83,2015,July,29,15,2,7,2,...,240.0,NaN,0,Transient,190.33,0,1,Check-Out,2015-07-24,4.0
434,Resort Hotel,1,66,2015,July,29,16,0,2,2,...,240.0,NaN,0,Transient,195.00,0,1,Canceled,2015-07-02,4.0
439,Resort Hotel,0,7,2015,July,29,16,0,1,2,...,242.0,NaN,0,Transient,169.00,1,1,Check-Out,2015-07-17,4.0
440,Resort Hotel,0,0,2015,July,29,16,0,2,2,...,NaN,NaN,0,Transient,198.00,1,0,Check-Out,2015-07-18,4.0
484,Resort Hotel,0,23,2015,July,29,17,2,5,2,...,250.0,NaN,0,Transient,195.00,0,0,Check-Out,2015-07-24,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118804,City Hotel,0,186,2017,August,33,19,2,5,2,...,9.0,NaN,0,Transient,218.43,0,0,Check-Out,2017-08-26,4.0
118832,City Hotel,0,163,2017,August,34,23,0,3,2,...,14.0,NaN,0,Transient,200.00,0,1,Check-Out,2017-08-26,4.0
118845,City Hotel,0,215,2017,August,34,25,0,1,2,...,14.0,NaN,0,Transient,215.00,0,0,Check-Out,2017-08-26,4.0
118852,City Hotel,0,215,2017,August,34,25,0,1,2,...,14.0,NaN,0,Transient,245.00,0,1,Check-Out,2017-08-26,5.0
118906,City Hotel,0,224,2017,August,34,24,0,3,2,...,14.0,NaN,0,Transient,163.50,0,3,Check-Out,2017-08-27,4.0
118920,City Hotel,0,131,2017,August,34,25,0,2,2,...,9.0,NaN,0,Transient,244.00,0,0,Check-Out,2017-08-27,4.0
118947,City Hotel,0,175,2017,August,33,19,2,6,1,...,9.0,NaN,0,Transient,160.76,0,0,Check-Out,2017-08-27,2.0
118957,City Hotel,0,112,2017,August,34,25,0,2,2,...,9.0,NaN,0,Transient,235.00,0,0,Check-Out,2017-08-27,4.0
118958,City Hotel,0,0,2017,August,34,26,0,1,2,...,NaN,NaN,0,Transient,200.00,0,0,Check-Out,2017-08-27,4.0
118959,City Hotel,0,216,2017,August,34,21,1,5,1,...,7.0,NaN,0,Transient,90.09,0,2,Check-Out,2017-08-27,2.0
118976,City Hotel,0,218,2017,August,33,18,3,7,2,...,14.0,NaN,0,Transient,215.86,0,1,Check-Out,2017-08-28,4.0
119031,City Hotel,0,164,2017,August,34,24,1,3,2,...,9.0,NaN,0,Transient,235.00,0,0,Check-Out,2017-08-28,4.0
119052,City Hotel,0,35,2017,August,34,26,2,1,2,...,14.0,NaN,0,Transient,176.64,0,1,Check-Out,2017-08-29,4.0
119054,City Hotel,0,8,2017,August,34,26,2,1,2,...,7.0,NaN,0,Transient,253.51,0,2,Check-Out,2017-08-29,5.0
119058,City Hotel,0,301,2017,August,35,27,2,0,2,...,9.0,NaN,0,Transient,179.10,0,0,Check-Out,2017-08-29,4.0
119070,City Hotel,0,0,2017,August,35,29,0,1,2,...,229.0,NaN,0,Group,270.00,0,1,Check-Out,2017-08-30,5.0
119077,City Hotel,0,221,2017,August,34,26,2,1,2,...,9.0,NaN,0,Transient,198.00,0,1,Check-Out,2017-08-29,4.0
119120,City Hotel,0,202,2017,August,34,26,2,2,1,...,9.0,NaN,0,Transient,117.00,0,0,Check-Out,2017-08-30,2.0
119126,City Hotel,0,130,2017,August,34,23,2,5,2,...,14.0,NaN,0,Transient,300.00,0,1,Check-Out,2017-08-30,4.0
119144,City Hotel,0,5,2017,August,35,29,0,1,2,...,9.0,NaN,0,Transient,259.00,0,0,Check-Out,2017-08-30,4.0
119151,City Hotel,0,0,2017,August,35,29,0,1,2,...,NaN,NaN,0,Transient,270.00,0,0,Check-Out,2017-08-30,4.0
119152,City Hotel,0,29,2017,August,35,27,2,1,2,...,9.0,NaN,0,Transient,233.00,0,0,Check-Out,2017-08-30,4.0
119153,City Hotel,0,22,2017,August,35,30,0,3,2,...,9.0,NaN,0,Transient,61.80,0,0,Check-Out,2017-09-02,4.0
119174,City Hotel,0,175,2017,August,35,27,2,2,1,...,9.0,NaN,0,Transient,175.50,0,1,Check-Out,2017-08-31,3.0
119223,City Hotel,0,6,2017,August,35,28,1,3,2,...,7.0,NaN,0,Transient,190.00,0,1,Check-Out,2017-09-01,4.0
119247,City Hotel,0,140,2017,August,35,27,2,3,2,...,9.0,NaN,0,Transient,235.00,0,0,Check-Out,2017-09-01,4.0
119251,City Hotel,0,140,2017,August,35,27,2,3,2,...,9.0,NaN,0,Transient,235.00,0,0,Check-Out,2017-09-01,4.0
119254,City Hotel,0,9,2017,August,35,28,1,3,2,...,14.0,NaN,0,Transient,210.00,0,0,Check-Out,2017-09-01,4.0
119293,City Hotel,0,243,2017,August,35,30,0,3,2,...,9.0,NaN,0,Transient,189.00,0,3,Check-Out,2017-09-02,4.0
119319,City Hotel,0,45,2017,August,35,28,1,5,2,...,7.0,NaN,0,Transient,194.13,0,1,Check-Out,2017-09-03,4.0

In [77]:
data.query('["Direct", "Corporate"] not in distribution_channel')  # 等同于 ' distribution_channel == ["Direct", "Corporate"]'

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,tags
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03,2.0
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03,2.0
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,240.0,NaN,0,Transient,82.00,0,1,Canceled,2015-05-06,2.0
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,15.0,NaN,0,Transient,105.50,0,0,Canceled,2015-04-22,2.0
10,Resort Hotel,1,23,2015,July,27,1,0,4,2,...,240.0,NaN,0,Transient,123.00,0,0,Canceled,2015-06-23,2.0
11,Resort Hotel,0,35,2015,July,27,1,0,4,2,...,240.0,NaN,0,Transient,145.00,0,0,Check-Out,2015-07-05,2.0
12,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,240.0,NaN,0,Transient,97.00,0,3,Check-Out,2015-07-05,2.0
13,Resort Hotel,0,18,2015,July,27,1,0,4,2,...,241.0,NaN,0,Transient,154.77,0,1,Check-Out,2015-07-05,3.0
14,Resort Hotel,0,37,2015,July,27,1,0,4,2,...,241.0,NaN,0,Transient,94.71,0,0,Check-Out,2015-07-05,2.0
15,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,240.0,NaN,0,Transient,97.00,0,3,Check-Out,2015-07-05,2.0
16,Resort Hotel,0,37,2015,July,27,1,0,4,2,...,8.0,NaN,0,Contract,97.50,0,0,Check-Out,2015-07-05,2.0
17,Resort Hotel,0,12,2015,July,27,1,0,1,2,...,240.0,NaN,0,Transient,88.20,0,0,Check-Out,2015-07-02,2.0
20,Resort Hotel,0,37,2015,July,27,1,1,4,1,...,241.0,NaN,0,Transient,97.29,0,1,Check-Out,2015-07-06,1.0
24,Resort Hotel,0,127,2015,July,27,1,2,5,2,...,115.0,NaN,0,Contract,94.95,0,1,Check-Out,2015-07-01,2.0
25,Resort Hotel,0,78,2015,July,27,1,2,5,2,...,5.0,NaN,0,Transient,63.60,1,0,Check-Out,2015-07-08,2.0
26,Resort Hotel,0,48,2015,July,27,1,2,5,2,...,8.0,NaN,0,Contract,79.50,0,0,Check-Out,2015-07-08,2.0
27,Resort Hotel,1,60,2015,July,27,1,2,5,2,...,240.0,NaN,0,Transient,107.00,0,2,Canceled,2015-05-11,2.0
28,Resort Hotel,0,77,2015,July,27,1,2,5,2,...,240.0,NaN,0,Transient,94.00,0,0,Check-Out,2015-07-08,2.0
29,Resort Hotel,0,99,2015,July,27,1,2,5,2,...,240.0,NaN,0,Transient,87.30,1,1,Check-Out,2015-07-08,2.0
31,Resort Hotel,0,95,2015,July,27,1,4,11,2,...,241.0,NaN,0,Transient,63.86,0,0,Check-Out,2015-07-16,2.0
33,Resort Hotel,0,69,2015,July,27,2,2,4,2,...,175.0,NaN,0,Transient,65.50,0,0,Check-Out,2015-07-08,2.0
34,Resort Hotel,1,45,2015,July,27,2,1,3,3,...,241.0,NaN,0,Transient,108.80,0,1,Canceled,2015-05-19,3.0
35,Resort Hotel,1,40,2015,July,27,2,1,3,3,...,241.0,NaN,0,Transient,108.80,0,1,Canceled,2015-06-19,3.0
36,Resort Hotel,0,15,2015,July,27,2,1,3,2,...,240.0,NaN,0,Transient,98.00,0,0,Check-Out,2015-07-06,2.0
37,Resort Hotel,0,36,2015,July,27,2,1,3,3,...,241.0,NaN,0,Transient,108.80,0,1,Check-Out,2015-07-06,3.0
38,Resort Hotel,1,43,2015,July,27,2,1,3,3,...,241.0,NaN,0,Transient,108.80,0,0,Canceled,2015-05-23,3.0
40,Resort Hotel,1,45,2015,July,27,2,2,3,2,...,241.0,NaN,0,Transient,117.81,0,0,Canceled,2015-05-18,2.0
41,Resort Hotel,0,45,2015,July,27,2,2,3,2,...,8.0,NaN,0,Contract,79.50,0,0,Check-Out,2015-07-07,2.0
44,Resort Hotel,0,107,2015,July,27,2,2,5,2,...,240.0,NaN,0,Transient,110.70,0,2,Check-Out,2015-07-09,2.0
45,Resort Hotel,1,47,2015,July,27,2,2,5,2,...,240.0,NaN,0,Transient,153.00,0,0,Canceled,2015-06-02,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119353,City Hotel,0,63,2017,August,35,31,0,3,3,...,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03,3.0
119354,City Hotel,0,63,2017,August,35,31,0,3,3,...,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03,3.0
119357,City Hotel,0,47,2017,August,35,31,1,3,1,...,423.0,NaN,0,Transient,91.02,0,0,Check-Out,2017-09-04,1.0
119359,City Hotel,0,63,2017,August,35,31,1,3,2,...,9.0,NaN,0,Transient,133.50,0,1,Check-Out,2017-09-04,2.0
119360,City Hotel,0,195,2017,August,35,29,1,5,2,...,9.0,NaN,0,Transient,117.00,0,1,Check-Out,2017-09-04,2.0
119361,City Hotel,0,100,2017,August,35,31,1,3,2,...,16.0,NaN,0,Transient,95.85,0,0,Check-Out,2017-09-04,2.0
119362,City Hotel,0,198,2017,August,35,29,1,5,2,...,9.0,NaN,0,Transient,119.17,0,2,Check-Out,2017-09-04,2.0
119363,City Hotel,0,212,2017,August,35,28,2,5,2,...,7.0,NaN,0,Transient,92.17,0,1,Check-Out,2017-09-04,2.0
119364,City Hotel,0,212,2017,August,35,28,2,5,2,...,7.0,NaN,0,Transient,92.17,0,2,Check-Out,2017-09-04,2.0
119366,City Hotel,0,210,2017,August,35,28,2,5,2,...,7.0,NaN,0,Transient,85.59,0,1,Check-Out,2017-09-04,2.0
119367,City Hotel,0,212,2017,August,35,28,2,5,2,...,7.0,NaN,0,Transient,85.59,0,0,Check-Out,2017-09-04,2.0
119370,City Hotel,0,201,2017,August,35,30,1,4,1,...,9.0,NaN,0,Transient,108.00,0,2,Check-Out,2017-09-04,1.0
119371,City Hotel,0,175,2017,August,35,31,1,3,2,...,42.0,NaN,0,Transient,86.85,0,2,Check-Out,2017-09-04,2.0
119372,City Hotel,0,175,2017,August,35,31,1,3,1,...,42.0,NaN,0,Transient,82.35,0,1,Check-Out,2017-09-04,1.0
119373,City Hotel,0,175,2017,August,35,31,1,3,1,...,42.0,NaN,0,Transient,82.35,0,1,Check-Out,2017-09-04,1.0
119374,City Hotel,0,201,2017,August,35,29,1,5,2,...,9.0,NaN,0,Transient,117.00,0,2,Check-Out,2017-09-04,2.0
119375,City Hotel,0,200,2017,August,35,30,1,4,2,...,16.0,NaN,0,Transient,85.50,0,1,Check-Out,2017-09-04,2.0
119376,City Hotel,0,165,2017,August,35,29,1,5,3,...,9.0,NaN,0,Transient,209.25,0,3,Check-Out,2017-09-04,3.0
119377,City Hotel,0,185,2017,August,35,30,1,4,2,...,9.0,NaN,0,Transient,99.00,0,1,Check-Out,2017-09-04,2.0
119378,City Hotel,0,247,2017,August,35,31,1,3,2,...,42.0,NaN,0,Transient,86.85,0,0,Check-Out,2017-09-04,2.0
119379,City Hotel,0,109,2017,August,35,31,1,3,2,...,9.0,NaN,0,Transient,155.00,0,1,Check-Out,2017-09-04,2.0
119380,City Hotel,0,44,2017,August,35,31,1,3,2,...,9.0,NaN,0,Transient,140.75,0,1,Check-Out,2017-09-04,2.0
119382,City Hotel,0,135,2017,August,35,30,2,4,3,...,7.0,NaN,0,Transient,209.00,0,0,Check-Out,2017-09-05,3.0
119383,City Hotel,0,164,2017,August,35,31,2,4,2,...,42.0,NaN,0,Transient,87.60,0,0,Check-Out,2017-09-06,2.0
119384,City Hotel,0,21,2017,August,35,30,2,5,2,...,394.0,NaN,0,Transient,96.14,0,2,Check-Out,2017-09-06,2.0
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06,2.0
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07,3.0
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07,2.0
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07,2.0
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07,2.0